<?php
/**
 * Plugin Name: LOIQ WordPress Agent
 * Description: Beveiligde REST API endpoints voor Claude CLI site debugging + write capabilities met safeguards.
 * Version: 3.0.1
 * Update URI: https://github.com/LOIQ-ai/loiq-wp-assistent
 * Author: LOIQ
 * Author URI: https://loiq.nl
 * License: GPL v2 or later
 * Requires PHP: 7.4
 */

if (!defined('ABSPATH')) exit;

define('LOIQ_AGENT_VERSION', '3.0.1');
define('LOIQ_AGENT_DB_VERSION', '2.0.0');
define('LOIQ_AGENT_GITHUB_REPO', 'LOIQ-ai/loiq-wp-assistent');
define('LOIQ_AGENT_PATH', plugin_dir_path(__FILE__));

// Load v2.0 includes
require_once LOIQ_AGENT_PATH . 'includes/class-safeguards.php';
require_once LOIQ_AGENT_PATH . 'includes/class-audit.php';
require_once LOIQ_AGENT_PATH . 'includes/class-write-endpoints.php';

// Load v3.0 includes
require_once LOIQ_AGENT_PATH . 'includes/class-divi-builder.php';
require_once LOIQ_AGENT_PATH . 'includes/class-divi-theme-builder.php';
require_once LOIQ_AGENT_PATH . 'includes/class-page-endpoints.php';
require_once LOIQ_AGENT_PATH . 'includes/class-child-theme.php';
require_once LOIQ_AGENT_PATH . 'includes/class-menu-endpoints.php';
require_once LOIQ_AGENT_PATH . 'includes/class-media-endpoints.php';
require_once LOIQ_AGENT_PATH . 'includes/class-forms-endpoints.php';
require_once LOIQ_AGENT_PATH . 'includes/class-facet-endpoints.php';
require_once LOIQ_AGENT_PATH . 'includes/class-taxonomy-endpoints.php';

/**
 * Main Plugin Class
 */
class LOIQ_WP_Agent {

    private static $instance = null;

    // Rate limits
    const RATE_LIMIT_MINUTE = 30;
    const RATE_LIMIT_HOUR = 300;

    // Default auto-disable hours
    const DEFAULT_HOURS = 24;

    // mu-plugin filename
    const MU_PLUGIN_FILE = 'loiq-agent-logging.php';

    public static function get_instance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Plugin activation - generate token and create tables
     */
    public static function on_activation() {
        // Generate secure token
        $token = bin2hex(random_bytes(32));

        // Store hashed token (never store plain text)
        update_option('loiq_agent_token_hash', password_hash($token, PASSWORD_DEFAULT));

        // Store plain token temporarily for one-time display
        set_transient('loiq_agent_new_token', $token, 300); // 5 minutes

        // Enable for default hours
        update_option('loiq_agent_enabled_until', time() + (self::DEFAULT_HOURS * 3600));

        // Create log table
        self::create_tables();

        // Install mu-plugin for managed debug logging
        self::install_mu_plugin();

        // Redirect to settings page to show token
        set_transient('loiq_agent_activation_redirect', true, 30);
    }

    /**
     * Plugin deactivation
     */
    public static function on_deactivation() {
        // Clear transients
        delete_transient('loiq_agent_new_token');
        delete_transient('loiq_agent_activation_redirect');

        // Remove mu-plugin
        self::remove_mu_plugin();
    }

    /**
     * Install mu-plugin that manages WP_DEBUG_LOG via our timer.
     * Returns true on success, error message on failure.
     */
    public static function install_mu_plugin() {
        $mu_dir = ABSPATH . 'wp-content/mu-plugins';
        $mu_file = $mu_dir . '/' . self::MU_PLUGIN_FILE;

        // Create mu-plugins dir if needed
        if (!is_dir($mu_dir)) {
            if (!wp_mkdir_p($mu_dir)) {
                return 'Kan mu-plugins directory niet aanmaken';
            }
        }

        $content = <<<'MUPHP'
<?php
/**
 * LOIQ WP Agent - Managed Debug Logging
 * Version: %%VERSION%%
 *
 * Enables PHP error logging when the LOIQ WP Agent timer is active.
 * Disables logging when the timer expires. No wp-config.php editing needed.
 *
 * @generated by LOIQ WP Agent plugin — do not edit
 */
if (!defined('ABSPATH')) exit;

// Escape hatch: define('LOIQ_AGENT_UNMANAGED', true) in wp-config.php
if (defined('LOIQ_AGENT_UNMANAGED') && LOIQ_AGENT_UNMANAGED) {
    return;
}

$loiq_timer = (int) get_option('loiq_agent_enabled_until', 0);
$loiq_active = ($loiq_timer > 0 && time() < $loiq_timer);

if ($loiq_active) {
    // Timer actief: enable debug logging
    error_reporting(E_ALL);
    @ini_set('log_errors', '1');
    @ini_set('error_log', WP_CONTENT_DIR . '/debug.log');
    @ini_set('display_errors', '0');

    if (!defined('WP_DEBUG'))         define('WP_DEBUG', true);
    if (!defined('WP_DEBUG_LOG'))     define('WP_DEBUG_LOG', true);
    if (!defined('WP_DEBUG_DISPLAY')) define('WP_DEBUG_DISPLAY', false);
} else {
    // Timer verlopen: disable debug logging
    @ini_set('log_errors', '0');
    @ini_set('display_errors', '0');

    if (!defined('WP_DEBUG'))         define('WP_DEBUG', false);
    if (!defined('WP_DEBUG_LOG'))     define('WP_DEBUG_LOG', false);
    if (!defined('WP_DEBUG_DISPLAY')) define('WP_DEBUG_DISPLAY', false);
}
MUPHP;

        // Inject version (nowdoc doesn't interpolate)
        $content = str_replace('%%VERSION%%', LOIQ_AGENT_VERSION, $content);

        if (file_put_contents($mu_file, $content) === false) {
            return 'Kan mu-plugin niet schrijven naar ' . $mu_file;
        }

        return true;
    }

    /**
     * Remove the mu-plugin file.
     */
    public static function remove_mu_plugin() {
        $mu_file = ABSPATH . 'wp-content/mu-plugins/' . self::MU_PLUGIN_FILE;
        if (file_exists($mu_file)) {
            @unlink($mu_file);
        }
    }

    /**
     * Install or update mu-plugin if missing or outdated.
     * Runs on every load so updates via WP auto-updater are picked up.
     */
    private function maybe_update_mu_plugin() {
        $mu_file = ABSPATH . 'wp-content/mu-plugins/' . self::MU_PLUGIN_FILE;

        // Check if mu-plugin exists and contains current version
        if (file_exists($mu_file)) {
            $content = file_get_contents($mu_file);
            if (strpos($content, LOIQ_AGENT_VERSION) !== false) {
                return; // Up to date
            }
        }

        // Missing or outdated — (re)install
        self::install_mu_plugin();
    }

    /**
     * Create database tables
     */
    private static function create_tables() {
        global $wpdb;
        $charset = $wpdb->get_charset_collate();

        $log_table = $wpdb->prefix . 'loiq_agent_log';
        $sql_log = "CREATE TABLE $log_table (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            endpoint VARCHAR(100) NOT NULL,
            ip_address VARCHAR(45) NOT NULL,
            response_code SMALLINT NOT NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY endpoint (endpoint),
            KEY created_at (created_at)
        ) $charset;";

        $snapshot_table = $wpdb->prefix . 'loiq_agent_snapshots';
        $sql_snapshots = "CREATE TABLE $snapshot_table (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            action_type VARCHAR(50) NOT NULL,
            target_key VARCHAR(255) NOT NULL,
            before_value LONGTEXT,
            after_value LONGTEXT,
            executed TINYINT(1) DEFAULT 0,
            rolled_back TINYINT(1) DEFAULT 0,
            session_id VARCHAR(64),
            ip_address VARCHAR(45),
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY action_type (action_type),
            KEY created_at (created_at),
            KEY session_id (session_id)
        ) $charset;";

        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        dbDelta($sql_log);
        dbDelta($sql_snapshots);

        update_option('loiq_agent_db_version', LOIQ_AGENT_DB_VERSION);
    }

    // Allowed email domains for admin visibility
    const ALLOWED_EMAIL_DOMAINS = ['ultrax.agency', 'teamultrax.nl', 'teamultrax.com'];

    private function __construct() {
        // Ensure mu-plugin is installed and current after updates
        $this->maybe_update_mu_plugin();

        // DB upgrade check (for updates without re-activation)
        $this->maybe_upgrade_db();

        // Activation redirect
        add_action('admin_init', [$this, 'activation_redirect']);

        // Register REST routes (v1 + v2 + v3) — token-based, no email restriction
        add_action('rest_api_init', [$this, 'register_routes']);

        // Admin menu (email-gated in callback)
        add_action('admin_menu', [$this, 'add_admin_menu']);

        // Admin assets
        add_action('admin_enqueue_scripts', [$this, 'enqueue_admin_assets']);

        // AJAX handlers (existing)
        add_action('wp_ajax_loiq_agent_regenerate_token', [$this, 'ajax_regenerate_token']);
        add_action('wp_ajax_loiq_agent_enable', [$this, 'ajax_enable']);
        add_action('wp_ajax_loiq_agent_disable', [$this, 'ajax_disable']);
        add_action('wp_ajax_loiq_agent_clear_log', [$this, 'ajax_clear_log']);
        add_action('wp_ajax_loiq_agent_install_mu', [$this, 'ajax_install_mu']);

        // AJAX handlers (v2.0)
        add_action('wp_ajax_loiq_agent_save_power_modes', [$this, 'ajax_save_power_modes']);
        add_action('wp_ajax_loiq_agent_rollback', [$this, 'ajax_rollback']);
        add_action('wp_ajax_loiq_agent_remove_snippet', [$this, 'ajax_remove_snippet']);

        // Hide plugin from plugins list for non-allowed users
        add_filter('all_plugins', [$this, 'filter_plugin_visibility']);
    }

    /**
     * Upgrade DB tables if version mismatch
     */
    private function maybe_upgrade_db() {
        $installed = get_option('loiq_agent_db_version', '0');
        if (version_compare($installed, LOIQ_AGENT_DB_VERSION, '<')) {
            self::create_tables();
        }
    }

    /**
     * Redirect to settings after activation
     */
    public function activation_redirect() {
        if (get_transient('loiq_agent_activation_redirect') && self::is_allowed_admin_user()) {
            delete_transient('loiq_agent_activation_redirect');
            wp_redirect(admin_url('tools.php?page=loiq-wp-agent'));
            exit;
        }
    }

    /**
     * Register REST API routes
     */
    public function register_routes() {
        $namespace = 'claude/v1';

        // status - no args
        register_rest_route($namespace, '/status', [
            'methods'             => 'GET',
            'callback'            => [$this, 'get_status'],
            'permission_callback' => [$this, 'check_permission'],
            'args'                => [],
        ]);

        // errors - optional lines param
        register_rest_route($namespace, '/errors', [
            'methods'             => 'GET',
            'callback'            => [$this, 'get_errors'],
            'permission_callback' => [$this, 'check_permission'],
            'args'                => [
                'lines' => [
                    'required'          => false,
                    'type'              => 'integer',
                    'default'           => 50,
                    'minimum'           => 1,
                    'maximum'           => 500,
                    'sanitize_callback' => 'absint',
                ],
            ],
        ]);

        // plugins - no args
        register_rest_route($namespace, '/plugins', [
            'methods'             => 'GET',
            'callback'            => [$this, 'get_plugins'],
            'permission_callback' => [$this, 'check_permission'],
            'args'                => [],
        ]);

        // theme - no args
        register_rest_route($namespace, '/theme', [
            'methods'             => 'GET',
            'callback'            => [$this, 'get_theme'],
            'permission_callback' => [$this, 'check_permission'],
            'args'                => [],
        ]);

        // database - no args
        register_rest_route($namespace, '/database', [
            'methods'             => 'GET',
            'callback'            => [$this, 'get_database'],
            'permission_callback' => [$this, 'check_permission'],
            'args'                => [],
        ]);

        // code-context - optional topic param
        register_rest_route($namespace, '/code-context', [
            'methods'             => 'GET',
            'callback'            => [$this, 'get_code_context'],
            'permission_callback' => [$this, 'check_permission'],
            'args'                => [
                'topic' => [
                    'required'          => false,
                    'type'              => 'string',
                    'default'           => 'general',
                    'sanitize_callback' => 'sanitize_text_field',
                    'validate_callback' => function($param) {
                        $allowed = ['gravity-forms', 'woocommerce', 'divi', 'acf', 'custom-post-types', 'rest-api', 'cron', 'general'];
                        return in_array($param, $allowed, true);
                    },
                ],
            ],
        ]);

        // styles - no args
        register_rest_route($namespace, '/styles', [
            'methods'             => 'GET',
            'callback'            => [$this, 'get_styles'],
            'permission_callback' => [$this, 'check_permission'],
            'args'                => [],
        ]);

        // forms - optional id param
        register_rest_route($namespace, '/forms', [
            'methods'             => 'GET',
            'callback'            => [$this, 'get_forms_detail'],
            'permission_callback' => [$this, 'check_permission'],
            'args'                => [
                'id' => [
                    'required'          => false,
                    'type'              => 'integer',
                    'default'           => 0,
                    'minimum'           => 0,
                    'sanitize_callback' => 'absint',
                ],
            ],
        ]);

        // page - optional url and id params
        register_rest_route($namespace, '/page', [
            'methods'             => 'GET',
            'callback'            => [$this, 'get_page_context'],
            'permission_callback' => [$this, 'check_permission'],
            'args'                => [
                'url' => [
                    'required'          => false,
                    'type'              => 'string',
                    'sanitize_callback' => 'sanitize_text_field',
                ],
                'id' => [
                    'required'          => false,
                    'type'              => 'integer',
                    'default'           => 0,
                    'minimum'           => 0,
                    'sanitize_callback' => 'absint',
                ],
            ],
        ]);

        // Register v2 write + management endpoints
        LOIQ_Agent_Write_Endpoints::register_routes($this);

        // Register v3 site builder endpoints
        LOIQ_Agent_Divi_Builder::register_routes($this);
        LOIQ_Agent_Divi_Theme_Builder::register_routes($this);
        LOIQ_Agent_Page_Endpoints::register_routes($this);
        LOIQ_Agent_Child_Theme::register_routes($this);
        LOIQ_Agent_Menu_Endpoints::register_routes($this);
        LOIQ_Agent_Media_Endpoints::register_routes($this);
        LOIQ_Agent_Forms_Endpoints::register_routes($this);
        LOIQ_Agent_Facet_Endpoints::register_routes($this);
        LOIQ_Agent_Taxonomy_Endpoints::register_routes($this);
    }

    /**
     * Permission callback for v2 write endpoints.
     * Extends check_permission with power mode + stricter rate limits.
     */
    public function check_write_permission(WP_REST_Request $request) {
        // 1. All base checks (HTTPS, timer, token, IP, read rate limit)
        $base_check = $this->check_permission($request);
        if (is_wp_error($base_check)) return $base_check;

        // 2. Power mode check for this action category
        $category = $this->get_write_category($request);
        if ($category && !LOIQ_Agent_Safeguards::is_enabled($category)) {
            return new WP_Error('power_mode_off',
                "Power mode voor '{$category}' is uitgeschakeld. Enable via wp-admin.",
                ['status' => 403]
            );
        }

        // 3. Stricter rate limit for writes
        $client_ip = $this->get_client_ip();
        $write_limit = LOIQ_Agent_Safeguards::check_write_rate_limit($client_ip);
        if (is_wp_error($write_limit)) return $write_limit;

        return true;
    }

    /**
     * Determine the power mode category from a write request route.
     *
     * @param WP_REST_Request $request
     * @return string|null
     */
    private function get_write_category(WP_REST_Request $request) {
        $route = $request->get_route();

        // v2 routes
        if (strpos($route, '/css/') !== false) return 'css';
        if (strpos($route, '/option/') !== false) return 'options';
        if (strpos($route, '/plugin/') !== false) return 'plugins';
        if (strpos($route, '/content/') !== false) return 'content';
        if (strpos($route, '/snippet/') !== false) return 'snippets';

        // v3 routes
        if (strpos($route, '/divi/build') !== false) return 'divi_builder';
        if (strpos($route, '/divi/library/save') !== false) return 'divi_builder';
        if (strpos($route, '/theme-builder/') !== false) return 'divi_builder';
        if (strpos($route, '/child-theme/') !== false) return 'child_theme';
        if (strpos($route, '/menu/') !== false) return 'menus';
        if (strpos($route, '/media/upload') !== false) return 'media';
        if (strpos($route, '/forms/') !== false) return 'forms';
        if (strpos($route, '/facet/') !== false) return 'facets';
        if (strpos($route, '/page/create') !== false) return 'content';
        if (strpos($route, '/page/clone') !== false) return 'content';
        if (strpos($route, '/taxonomy/create-term') !== false) return 'content';
        if (strpos($route, '/taxonomy/assign') !== false) return 'content';

        // Rollback: check the snapshot's action type
        if (strpos($route, '/rollback') !== false) return null; // Allow rollback regardless

        return null;
    }

    /**
     * Security permission callback - ALL checks here
     */
    public function check_permission(WP_REST_Request $request) {
        // 1. HTTPS check (allow localhost for dev)
        $is_localhost = in_array(sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'] ?? '')), ['127.0.0.1', '::1']);
        if (!is_ssl() && !$is_localhost) {
            $this->log_request($request->get_route(), 403);
            return new WP_Error('https_required', 'HTTPS is verplicht', ['status' => 403]);
        }

        // 2. Auto-disable check
        $enabled_until = (int) get_option('loiq_agent_enabled_until', 0);
        if ($enabled_until > 0 && time() > $enabled_until) {
            $this->log_request($request->get_route(), 503);
            return new WP_Error('disabled', 'Debug endpoint is uitgeschakeld (timer verlopen)', ['status' => 503]);
        }

        // 3. Auth lockout check — block IP after 5 failed attempts (15 min cooldown)
        $client_ip_for_lockout = sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'] ?? '0.0.0.0'));
        $lockout_key = 'loiq_agent_lockout_' . md5($client_ip_for_lockout);
        $failed_attempts = (int) get_transient($lockout_key);
        if ($failed_attempts >= 5) {
            $this->log_request($request->get_route(), 403);
            return new WP_Error('auth_lockout', 'Te veel mislukte pogingen. Probeer over 15 minuten opnieuw.', ['status' => 403]);
        }

        // 4. Token verification (primary) OR WP Application Password (fallback)
        $token = $request->get_header('X-Claude-Token');
        $authenticated = false;

        if (!empty($token)) {
            // Primary auth: LOIQ token
            $hash = get_option('loiq_agent_token_hash', '');
            if (empty($hash) || !password_verify($token, $hash)) {
                set_transient($lockout_key, $failed_attempts + 1, 900);
                $this->log_request($request->get_route(), 401);
                return new WP_Error('invalid_token', 'Ongeldig token', ['status' => 401]);
            }
            $authenticated = true;
        } else {
            // Fallback auth: WP Application Password (requires manage_options)
            $user = wp_get_current_user();
            if ($user->ID > 0 && user_can($user, 'manage_options')) {
                $authenticated = true;
            }
        }

        if (!$authenticated) {
            set_transient($lockout_key, $failed_attempts + 1, 900);
            $this->log_request($request->get_route(), 401);
            return new WP_Error('missing_token', 'X-Claude-Token header of geldige WP authenticatie vereist', ['status' => 401]);
        }

        // Reset lockout on successful auth
        delete_transient($lockout_key);

        // 4. IP whitelist (if configured)
        $whitelist = get_option('loiq_agent_ip_whitelist', '');
        if (!empty($whitelist)) {
            $allowed_ips = array_map('trim', explode("\n", $whitelist));
            $client_ip = $this->get_client_ip();
            if (!in_array($client_ip, $allowed_ips)) {
                $this->log_request($request->get_route(), 403);
                return new WP_Error('ip_blocked', 'IP niet toegestaan', ['status' => 403]);
            }
        }

        // 5. Rate limiting
        $client_ip = $this->get_client_ip();
        $ip_hash = md5($client_ip);

        // Per minute
        $minute_key = 'loiq_agent_rate_m_' . $ip_hash;
        $minute_count = (int) get_transient($minute_key);
        if ($minute_count >= self::RATE_LIMIT_MINUTE) {
            $this->log_request($request->get_route(), 429);
            return new WP_Error('rate_limit', 'Te veel requests (max ' . self::RATE_LIMIT_MINUTE . '/min)', ['status' => 429]);
        }

        // Per hour
        $hour_key = 'loiq_agent_rate_h_' . $ip_hash;
        $hour_count = (int) get_transient($hour_key);
        if ($hour_count >= self::RATE_LIMIT_HOUR) {
            $this->log_request($request->get_route(), 429);
            return new WP_Error('rate_limit', 'Te veel requests (max ' . self::RATE_LIMIT_HOUR . '/uur)', ['status' => 429]);
        }

        // Increment counters
        set_transient($minute_key, $minute_count + 1, 60);
        set_transient($hour_key, $hour_count + 1, 3600);

        // Log successful request
        $this->log_request($request->get_route(), 200);

        return true;
    }

    /**
     * Get client IP — secure against header spoofing.
     *
     * Only trusts REMOTE_ADDR by default. Proxy headers (CF, X-Forwarded-For)
     * are only used when trusted_proxy_ip is configured in admin, AND the
     * request actually comes from that proxy IP.
     */
    private function get_client_ip() {
        $ip = sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'] ?? '0.0.0.0'));

        // Only trust proxy headers when request comes from a known proxy
        $trusted_proxy = get_option('loiq_agent_trusted_proxy', '');
        if (!empty($trusted_proxy) && trim($ip) === trim($trusted_proxy)) {
            $proxy_headers = ['HTTP_CF_CONNECTING_IP', 'HTTP_X_FORWARDED_FOR', 'HTTP_X_REAL_IP'];
            foreach ($proxy_headers as $header) {
                if (!empty($_SERVER[$header])) {
                    $forwarded = sanitize_text_field(wp_unslash(explode(',', $_SERVER[$header])[0]));
                    if (filter_var(trim($forwarded), FILTER_VALIDATE_IP)) {
                        $ip = $forwarded;
                    }
                    break;
                }
            }
        }

        return trim($ip);
    }

    /**
     * Log request to database
     */
    private function log_request($endpoint, $response_code) {
        global $wpdb;
        $table = $wpdb->prefix . 'loiq_agent_log';

        // Anonymize IP for GDPR (last octet = 0)
        $ip = $this->get_client_ip();
        $ip = preg_replace('/\.\d+$/', '.0', $ip);

        $wpdb->insert($table, [
            'endpoint'      => sanitize_text_field($endpoint),
            'ip_address'    => $ip,
            'response_code' => (int) $response_code,
            'created_at'    => current_time('mysql'),
        ], ['%s', '%s', '%d', '%s']);
    }

    // =========================================================================
    // REST ENDPOINTS
    // =========================================================================

    /**
     * GET /claude/v1/status - Site health info
     */
    public function get_status() {
        global $wpdb;

        return [
            'site_url'       => get_site_url(),
            'wp_version'     => get_bloginfo('version'),
            'php_version'    => PHP_VERSION,
            'mysql_version'  => $wpdb->db_version(),
            'memory_limit'   => WP_MEMORY_LIMIT,
            'debug_mode'     => WP_DEBUG,
            'debug_log'      => defined('WP_DEBUG_LOG') && WP_DEBUG_LOG,
            'multisite'      => is_multisite(),
            'ssl'            => is_ssl(),
            'timezone'       => wp_timezone_string(),
            'active_plugins' => count(get_option('active_plugins', [])),
            'post_count'     => wp_count_posts()->publish ?? 0,
            'page_count'     => wp_count_posts('page')->publish ?? 0,
            'user_count'     => count_users()['total_users'] ?? 0,
        ];
    }

    /**
     * GET /claude/v1/errors - Last N lines from debug.log
     */
    public function get_errors(WP_REST_Request $request) {
        $lines = (int) $request->get_param('lines') ?: 50;
        $lines = min($lines, 500); // Max 500 lines

        $log_file = WP_CONTENT_DIR . '/debug.log';

        if (!file_exists($log_file)) {
            return [
                'exists'  => false,
                'message' => 'debug.log niet gevonden. Zet WP_DEBUG_LOG aan in wp-config.php',
            ];
        }

        // Read last N lines efficiently
        $file = new SplFileObject($log_file, 'r');
        $file->seek(PHP_INT_MAX);
        $total_lines = $file->key();

        $start = max(0, $total_lines - $lines);
        $file->seek($start);

        $log_lines = [];
        while (!$file->eof()) {
            $line = trim($file->current());
            if (!empty($line)) {
                $log_lines[] = $line;
            }
            $file->next();
        }

        return [
            'exists'      => true,
            'total_lines' => $total_lines,
            'returned'    => count($log_lines),
            'lines'       => $log_lines,
        ];
    }

    /**
     * GET /claude/v1/plugins - Plugin list with update status
     */
    public function get_plugins() {
        if (!function_exists('get_plugins')) {
            require_once ABSPATH . 'wp-admin/includes/plugin.php';
        }

        $all_plugins = get_plugins();
        $active_plugins = get_option('active_plugins', []);

        // Get update info
        $updates = get_site_transient('update_plugins');
        $update_list = $updates->response ?? [];

        $result = [];
        foreach ($all_plugins as $file => $data) {
            $result[] = [
                'file'        => $file,
                'name'        => $data['Name'],
                'version'     => $data['Version'],
                'active'      => in_array($file, $active_plugins),
                'update'      => isset($update_list[$file]) ? $update_list[$file]->new_version : null,
                'author'      => strip_tags($data['Author']),
                'requires_wp' => $data['RequiresWP'] ?? null,
                'requires_php'=> $data['RequiresPHP'] ?? null,
            ];
        }

        return [
            'total'  => count($result),
            'active' => count($active_plugins),
            'updates'=> count($update_list),
            'plugins'=> $result,
        ];
    }

    /**
     * GET /claude/v1/theme - Active theme info
     */
    public function get_theme() {
        $theme = wp_get_theme();
        $parent = $theme->parent();

        // Get update info
        $updates = get_site_transient('update_themes');
        $update_available = isset($updates->response[$theme->get_stylesheet()]);

        return [
            'name'        => $theme->get('Name'),
            'version'     => $theme->get('Version'),
            'author'      => $theme->get('Author'),
            'template'    => $theme->get_template(),
            'stylesheet'  => $theme->get_stylesheet(),
            'is_child'    => $theme->parent() !== false,
            'parent'      => $parent ? [
                'name'    => $parent->get('Name'),
                'version' => $parent->get('Version'),
            ] : null,
            'update'      => $update_available ? $updates->response[$theme->get_stylesheet()]['new_version'] : null,
        ];
    }

    /**
     * GET /claude/v1/database - Database schema info (NO data!)
     */
    public function get_database() {
        global $wpdb;

        // Get all tables with prefix
        $tables = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT TABLE_NAME, TABLE_ROWS, DATA_LENGTH, INDEX_LENGTH
                 FROM information_schema.TABLES
                 WHERE TABLE_SCHEMA = %s AND TABLE_NAME LIKE %s",
                DB_NAME,
                $wpdb->prefix . '%'
            )
        );

        $result = [];
        $total_size = 0;

        foreach ($tables as $table) {
            $size = (int) $table->DATA_LENGTH + (int) $table->INDEX_LENGTH;
            $total_size += $size;

            $result[] = [
                'name'  => $table->TABLE_NAME,
                'rows'  => (int) $table->TABLE_ROWS,
                'size'  => $this->format_bytes($size),
                'bytes' => $size,
            ];
        }

        return [
            'prefix'      => $wpdb->prefix,
            'total_tables'=> count($result),
            'total_size'  => $this->format_bytes($total_size),
            'total_bytes' => $total_size,
            'tables'      => $result,
        ];
    }

    /**
     * GET /claude/v1/code-context - Code context for specific topics
     */
    public function get_code_context(WP_REST_Request $request) {
        $topic = sanitize_text_field($request->get_param('topic') ?: 'general');

        // Topic configurations
        $topics = [
            'gravity-forms' => [
                'patterns' => ['gform_', 'GF_', 'gravityforms'],
                'plugin'   => 'gravityforms/gravityforms.php',
                'hooks'    => ['gform_after_submission', 'gform_pre_render', 'gform_field_validation', 'gform_pre_submission'],
            ],
            'woocommerce' => [
                'patterns' => ['wc_', 'woocommerce_', 'WC_'],
                'plugin'   => 'woocommerce/woocommerce.php',
                'hooks'    => ['woocommerce_checkout_process', 'woocommerce_payment_complete', 'woocommerce_add_to_cart'],
            ],
            'divi' => [
                'patterns' => ['et_', 'divi_', 'ET_Builder'],
                'theme'    => 'Divi',
                'hooks'    => ['et_after_main_content', 'et_before_main_content', 'et_pb_module_shortcode_attributes'],
            ],
            'acf' => [
                'patterns' => ['acf/', 'acf_', 'get_field', 'the_field'],
                'plugin'   => 'advanced-custom-fields-pro/acf.php',
                'hooks'    => ['acf/save_post', 'acf/load_field', 'acf/update_value'],
            ],
            'custom-post-types' => [
                'patterns' => ['register_post_type', 'register_taxonomy'],
                'hooks'    => [],
            ],
            'rest-api' => [
                'patterns' => ['register_rest_route', 'rest_api_init'],
                'hooks'    => ['rest_api_init', 'rest_pre_dispatch'],
            ],
            'cron' => [
                'patterns' => ['wp_schedule_event', 'wp_cron'],
                'hooks'    => [],
            ],
            'general' => [
                'patterns' => ['add_action', 'add_filter', 'do_action', 'apply_filters'],
                'hooks'    => [],
            ],
        ];

        $config = $topics[$topic] ?? $topics['general'];
        $result = [
            'topic'     => $topic,
            'available_topics' => array_keys($topics),
        ];

        // Check if related plugin is active
        if (!empty($config['plugin'])) {
            if (!function_exists('is_plugin_active')) {
                require_once ABSPATH . 'wp-admin/includes/plugin.php';
            }
            $result['plugin_active'] = is_plugin_active($config['plugin']);

            // Get plugin version
            if ($result['plugin_active']) {
                $plugin_data = get_plugin_data(WP_PLUGIN_DIR . '/' . $config['plugin']);
                $result['plugin_version'] = $plugin_data['Version'] ?? 'unknown';
            }
        }

        // Check if related theme is active
        if (!empty($config['theme'])) {
            $theme = wp_get_theme();
            $result['theme_match'] = (
                stripos($theme->get('Name'), $config['theme']) !== false ||
                stripos($theme->get_template(), strtolower($config['theme'])) !== false
            );
        }

        // Scan functions.php for hooks
        $theme_dir = get_stylesheet_directory();
        $functions_file = $theme_dir . '/functions.php';
        $result['theme_hooks'] = [];

        if (file_exists($functions_file)) {
            $result['theme_hooks'] = $this->scan_file_for_patterns($functions_file, $config['patterns']);
        }

        // Also check child theme if exists
        $parent_dir = get_template_directory();
        if ($parent_dir !== $theme_dir) {
            $parent_functions = $parent_dir . '/functions.php';
            if (file_exists($parent_functions)) {
                $parent_hooks = $this->scan_file_for_patterns($parent_functions, $config['patterns']);
                foreach ($parent_hooks as $hook) {
                    $hook['source'] = 'parent_theme';
                    $result['theme_hooks'][] = $hook;
                }
            }
        }

        // Get custom functions related to topic
        $result['custom_functions'] = $this->extract_function_names($result['theme_hooks']);

        // Topic-specific data
        if ($topic === 'gravity-forms' && class_exists('GFAPI')) {
            $forms = GFAPI::get_forms();
            $result['forms_count'] = count($forms);
            $result['forms_summary'] = array_map(function($f) {
                return [
                    'id'           => $f['id'],
                    'title'        => $f['title'],
                    'is_active'    => (bool) ($f['is_active'] ?? false),
                    'fields_count' => count($f['fields'] ?? []),
                    'css_class'    => $f['cssClass'] ?? '',
                ];
            }, array_slice($forms, 0, 10));

            // Active add-on feeds (Zapier, Mailchimp, etc.)
            if (method_exists('GFAPI', 'get_feeds')) {
                $feeds = GFAPI::get_feeds();
                $feed_summary = [];
                foreach (($feeds ?: []) as $feed) {
                    if (!empty($feed['is_active'])) {
                        $feed_summary[] = [
                            'addon_slug' => $feed['addon_slug'] ?? 'unknown',
                            'form_id'    => $feed['form_id'] ?? 0,
                        ];
                    }
                }
                $result['feeds'] = array_slice($feed_summary, 0, 20);
            }
        }

        if ($topic === 'woocommerce' && function_exists('wc_get_product')) {
            $result['product_count'] = wp_count_posts('product')->publish ?? 0;
            $result['order_count'] = wp_count_posts('shop_order')->publish ?? 0;
        }

        if ($topic === 'acf' && function_exists('acf_get_field_groups')) {
            $groups = acf_get_field_groups();
            $result['field_groups'] = count($groups);
            $result['field_group_titles'] = array_map(function($g) {
                return $g['title'];
            }, array_slice($groups, 0, 10));
        }

        if ($topic === 'divi') {
            $divi_options = get_option('et_divi', []);
            if (is_array($divi_options) && !empty($divi_options['custom_css'])) {
                $result['custom_css_length'] = strlen($divi_options['custom_css']);
            }
            // Count Divi Library items
            $library_count = wp_count_posts('et_pb_layout');
            $result['builder_layouts'] = (int) ($library_count->publish ?? 0);
        }

        if ($topic === 'custom-post-types') {
            $post_types = get_post_types(['_builtin' => false], 'objects');
            $result['custom_post_types'] = [];
            foreach ($post_types as $pt) {
                $result['custom_post_types'][] = [
                    'name'   => $pt->name,
                    'label'  => $pt->label,
                    'count'  => wp_count_posts($pt->name)->publish ?? 0,
                ];
            }
        }

        // Relevant documentation links
        $docs = [
            'gravity-forms' => 'https://docs.gravityforms.com/category/developers/',
            'woocommerce'   => 'https://woocommerce.github.io/code-reference/',
            'divi'          => 'https://www.elegantthemes.com/documentation/developers/',
            'acf'           => 'https://www.advancedcustomfields.com/resources/',
        ];
        $result['docs_url'] = $docs[$topic] ?? null;

        return $result;
    }

    /**
     * GET /claude/v1/styles - CSS environment context
     */
    public function get_styles() {
        $result = [
            'stylesheets'    => [],
            'customizer_css' => '',
            'child_theme_css'=> '',
            'divi_custom_css'=> null,
        ];

        // Registered stylesheets from wp_styles()
        global $wp_styles;
        if ($wp_styles instanceof WP_Styles) {
            foreach ($wp_styles->registered as $handle => $style) {
                $result['stylesheets'][] = [
                    'handle'  => $handle,
                    'src'     => $style->src ?: null,
                    'deps'    => $style->deps,
                    'version' => $style->ver,
                ];
            }
        }

        // Customizer CSS
        $result['customizer_css'] = wp_get_custom_css();

        // Child theme style.css (first 200 lines)
        $child_css_path = get_stylesheet_directory() . '/style.css';
        if (file_exists($child_css_path)) {
            $lines = file($child_css_path, FILE_IGNORE_NEW_LINES);
            $result['child_theme_css'] = implode("\n", array_slice($lines, 0, 200));
        }

        // Divi custom CSS (if Divi active)
        $divi_options = get_option('et_divi', []);
        if (is_array($divi_options) && !empty($divi_options['custom_css'])) {
            $result['divi_custom_css'] = $divi_options['custom_css'];
        }

        return $result;
    }

    /**
     * GET /claude/v1/forms - Gravity Forms detail
     */
    public function get_forms_detail(WP_REST_Request $request) {
        if (!class_exists('GFAPI')) {
            return new WP_Error('gf_not_active', 'Gravity Forms is niet actief', ['status' => 404]);
        }

        $form_id = (int) $request->get_param('id');

        // Single form detail
        if ($form_id > 0) {
            $form = GFAPI::get_form($form_id);
            if (!$form) {
                return new WP_Error('form_not_found', 'Formulier niet gevonden', ['status' => 404]);
            }

            $fields = [];
            foreach ($form['fields'] ?? [] as $field) {
                $field_data = [
                    'id'         => $field->id,
                    'type'       => $field->type,
                    'label'      => $field->label,
                    'cssClass'   => $field->cssClass,
                    'isRequired' => (bool) $field->isRequired,
                ];
                if (!empty($field->choices)) {
                    $field_data['choices'] = array_map(function($c) {
                        return ['text' => $c['text'], 'value' => $c['value']];
                    }, $field->choices);
                }
                $fields[] = $field_data;
            }

            return [
                'id'             => $form['id'],
                'title'          => $form['title'],
                'css_class'      => $form['cssClass'] ?? '',
                'is_active'      => (bool) ($form['is_active'] ?? false),
                'fields'         => $fields,
                'confirmations'  => array_values(array_map(function($c) {
                    return [
                        'type'    => $c['type'] ?? 'message',
                        'message' => isset($c['message']) ? wp_strip_all_tags(substr($c['message'], 0, 300)) : '',
                    ];
                }, $form['confirmations'] ?? [])),
                'notifications'  => array_values(array_map(function($n) {
                    return [
                        'name'    => $n['name'] ?? '',
                        'event'   => $n['event'] ?? '',
                        'to'      => $n['toType'] ?? 'email',
                        'subject' => $n['subject'] ?? '',
                        'is_active' => (bool) ($n['isActive'] ?? true),
                    ];
                }, $form['notifications'] ?? [])),
            ];
        }

        // All forms summary
        $forms = GFAPI::get_forms();
        $summary = [];
        foreach ($forms as $form) {
            $summary[] = [
                'id'           => $form['id'],
                'title'        => $form['title'],
                'is_active'    => (bool) ($form['is_active'] ?? false),
                'fields_count' => count($form['fields'] ?? []),
                'entries_count'=> (int) GFAPI::count_entries($form['id']),
            ];
        }

        return [
            'total' => count($summary),
            'forms' => $summary,
        ];
    }

    /**
     * GET /claude/v1/page - Page context by URL or ID
     */
    public function get_page_context(WP_REST_Request $request) {
        $url = $request->get_param('url');
        $post_id = (int) $request->get_param('id');

        // Resolve URL to post ID
        if (!empty($url) && $post_id === 0) {
            $full_url = home_url($url);
            $post_id = url_to_postid($full_url);
        }

        if ($post_id <= 0) {
            return new WP_Error('page_not_found', 'Pagina niet gevonden. Gebruik ?url=/pad of ?id=42', ['status' => 404]);
        }

        $post = get_post($post_id);
        if (!$post) {
            return new WP_Error('page_not_found', 'Pagina niet gevonden', ['status' => 404]);
        }

        $result = [
            'id'             => $post->ID,
            'title'          => $post->post_title,
            'slug'           => $post->post_name,
            'status'         => $post->post_status,
            'type'           => $post->post_type,
            'template'       => get_page_template_slug($post->ID) ?: 'default',
            'featured_image' => get_the_post_thumbnail_url($post->ID, 'full') ?: null,
            'content_preview'=> wp_strip_all_tags(substr($post->post_content, 0, 500)),
        ];

        // Meta keys (filtered for sensitive data)
        $sensitive_keys = ['password', 'secret', 'token', 'key', 'hash', 'nonce', 'auth'];
        $all_meta = get_post_meta($post->ID);
        $safe_meta_keys = [];
        foreach (array_keys($all_meta) as $meta_key) {
            $is_sensitive = false;
            foreach ($sensitive_keys as $sensitive) {
                if (stripos($meta_key, $sensitive) !== false) {
                    $is_sensitive = true;
                    break;
                }
            }
            if (!$is_sensitive) {
                $safe_meta_keys[] = $meta_key;
            }
        }
        $result['meta_keys'] = $safe_meta_keys;

        // Divi modules (if Divi builder content)
        if (strpos($post->post_content, '[et_pb_') !== false) {
            preg_match_all('/\[et_pb_(\w+)[\s\]]/', $post->post_content, $matches);
            $result['divi_modules'] = array_values(array_unique($matches[1] ?? []));
        }

        // Yoast SEO data
        $yoast_title = get_post_meta($post->ID, '_yoast_wpseo_title', true);
        $yoast_desc = get_post_meta($post->ID, '_yoast_wpseo_metadesc', true);
        if ($yoast_title || $yoast_desc) {
            $result['yoast'] = [
                'title'       => $yoast_title ?: null,
                'description' => $yoast_desc ?: null,
            ];
        }

        return $result;
    }

    /**
     * Scan a file for patterns and return matches with context
     */
    private function scan_file_for_patterns($file, $patterns) {
        $matches = [];
        $lines = file($file, FILE_IGNORE_NEW_LINES);

        foreach ($lines as $line_num => $line) {
            foreach ($patterns as $pattern) {
                if (stripos($line, $pattern) !== false) {
                    // Security: filter out sensitive data
                    if ($this->contains_sensitive_data($line)) {
                        continue;
                    }

                    // Extract hook name if it's an add_action/add_filter
                    $hook_name = $this->extract_hook_name($line);

                    $matches[] = [
                        'file'    => basename($file),
                        'line'    => $line_num + 1,
                        'hook'    => $hook_name,
                        'snippet' => $this->sanitize_snippet($line),
                        'source'  => 'child_theme',
                    ];
                    break; // Don't match same line multiple times
                }
            }
        }

        return array_slice($matches, 0, 50); // Max 50 matches
    }

    /**
     * Check if line contains sensitive data
     */
    private function contains_sensitive_data($line) {
        $sensitive_patterns = [
            '/api[_-]?key/i',
            '/secret/i',
            '/password/i',
            '/credential/i',
            '/token\s*=/i',
            '/auth/i',
            '/private[_-]?key/i',
            '/DB_PASSWORD/i',
            '/DB_USER/i',
        ];

        foreach ($sensitive_patterns as $pattern) {
            if (preg_match($pattern, $line)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Extract hook name from add_action/add_filter call
     */
    private function extract_hook_name($line) {
        if (preg_match('/add_(action|filter)\s*\(\s*[\'"]([^\'"]+)[\'"]/', $line, $matches)) {
            return $matches[2];
        }
        return null;
    }

    /**
     * Sanitize snippet for safe output
     */
    private function sanitize_snippet($line) {
        $line = trim($line);
        // Truncate long lines
        if (strlen($line) > 150) {
            $line = substr($line, 0, 147) . '...';
        }
        return $line;
    }

    /**
     * Extract function names from hook matches
     */
    private function extract_function_names($hooks) {
        $functions = [];
        foreach ($hooks as $hook) {
            // Match function name in callback
            if (preg_match('/[\'"]([a-zA-Z_][a-zA-Z0-9_]*)[\'"]/', $hook['snippet'], $matches)) {
                $func = $matches[1];
                // Skip common WordPress functions
                if (!in_array($func, ['__return_true', '__return_false', '__return_empty_array'])) {
                    $functions[] = $func . '()';
                }
            }
        }
        return array_unique($functions);
    }

    /**
     * Format bytes to human readable
     */
    private function format_bytes($bytes) {
        $units = ['B', 'KB', 'MB', 'GB'];
        $i = 0;
        while ($bytes >= 1024 && $i < count($units) - 1) {
            $bytes /= 1024;
            $i++;
        }
        return round($bytes, 2) . ' ' . $units[$i];
    }

    // =========================================================================
    // ADMIN
    // =========================================================================

    /**
     * Check if current user has an allowed email domain for admin access.
     *
     * Only users with @ultrax.agency, @teamultrax.nl, or @teamultrax.com emails
     * can see the plugin in wp-admin. REST API access is unaffected (token-based).
     *
     * @return bool
     */
    public static function is_allowed_admin_user() {
        $user = wp_get_current_user();
        if (!$user || !$user->exists()) {
            return false;
        }
        $email = strtolower($user->user_email);
        foreach (self::ALLOWED_EMAIL_DOMAINS as $domain) {
            if (substr($email, -strlen('@' . $domain)) === '@' . $domain) {
                return true;
            }
        }
        return false;
    }

    /**
     * Hide plugin from the plugins list for non-allowed users.
     *
     * @param array $plugins
     * @return array
     */
    public function filter_plugin_visibility($plugins) {
        if (!self::is_allowed_admin_user()) {
            unset($plugins['loiq-wp-agent/loiq-wp-agent.php']);
        }
        return $plugins;
    }

    /**
     * Add admin menu under Tools (only for allowed email domains)
     */
    public function add_admin_menu() {
        if (!self::is_allowed_admin_user()) {
            return;
        }
        add_submenu_page(
            'tools.php',
            'LOIQ WP Agent',
            'LOIQ WP Agent',
            'manage_options',
            'loiq-wp-agent',
            [$this, 'render_admin_page']
        );
    }

    /**
     * Enqueue admin assets
     */
    public function enqueue_admin_assets($hook) {
        if ($hook !== 'tools_page_loiq-wp-agent') {
            return;
        }

        wp_enqueue_style('loiq-wp-agent-admin', false);
        wp_add_inline_style('loiq-wp-agent-admin', $this->get_admin_css());
    }

    /**
     * Get admin CSS
     */
    private function get_admin_css() {
        return '
            .loiq-wp-agent-wrap { max-width: 800px; }
            .loiq-wp-agent-wrap h1 { color: #1d2327; margin-bottom: 20px; }
            .loiq-card { background: #fff; border: 1px solid #c3c4c7; border-radius: 4px; padding: 20px; margin-bottom: 20px; }
            .loiq-card h2 { margin-top: 0; padding-bottom: 10px; border-bottom: 1px solid #eee; }
            .loiq-token-display { background: #f0f0f1; padding: 15px; border-radius: 4px; font-family: monospace; font-size: 14px; word-break: break-all; margin: 15px 0; }
            .loiq-token-new { background: #d4edda; border: 1px solid #28a745; }
            .loiq-token-new::before { content: "NIEUW - Kopieer nu! "; font-weight: bold; color: #155724; }
            .loiq-status { display: inline-block; padding: 5px 12px; border-radius: 20px; font-weight: 500; }
            .loiq-status-active { background: #d4edda; color: #155724; }
            .loiq-status-inactive { background: #f8d7da; color: #721c24; }
            .loiq-btn { margin-right: 10px !important; }
            .loiq-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
            .loiq-table th, .loiq-table td { padding: 10px; text-align: left; border-bottom: 1px solid #eee; }
            .loiq-table th { background: #f6f7f7; font-weight: 500; }
            .loiq-code { font-family: monospace; font-size: 12px; background: #f0f0f1; padding: 2px 6px; border-radius: 3px; }
            .loiq-log-200 { color: #155724; }
            .loiq-log-401, .loiq-log-403, .loiq-log-429 { color: #721c24; }
            .loiq-log-503 { color: #856404; }
            .loiq-help { background: #e7f3fe; border-left: 4px solid #2271b1; padding: 12px 15px; margin: 15px 0; }
            .loiq-help code { background: #d4e5f7; }
            .loiq-power-modes label { display: block; padding: 8px 0; font-size: 14px; }
            .loiq-power-modes input[type="checkbox"] { margin-right: 8px; }
            .loiq-power-modes .description { color: #646970; margin-left: 26px; display: block; font-size: 12px; }
            .loiq-snapshot-actions { white-space: nowrap; }
            .loiq-badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 500; }
            .loiq-badge-executed { background: #d4edda; color: #155724; }
            .loiq-badge-dryrun { background: #fff3cd; color: #856404; }
            .loiq-badge-rollback { background: #d1ecf1; color: #0c5460; }
        ';
    }

    /**
     * Render admin page
     */
    public function render_admin_page() {
        // Get status
        $enabled_until = (int) get_option('loiq_agent_enabled_until', 0);
        $is_active = $enabled_until > time();
        $new_token = get_transient('loiq_agent_new_token');
        $mu_plugin_installed = file_exists(ABSPATH . 'wp-content/mu-plugins/' . self::MU_PLUGIN_FILE);

        // Get request log
        global $wpdb;
        $log_table = $wpdb->prefix . 'loiq_agent_log';
        $table_exists = $wpdb->get_var($wpdb->prepare("SHOW TABLES LIKE %s", $log_table)) === $log_table;
        $recent_requests = $table_exists ? $wpdb->get_results(
            $wpdb->prepare("SELECT * FROM {$wpdb->prefix}loiq_agent_log ORDER BY created_at DESC LIMIT %d", 20)
        ) : [];

        ?>
        <div class="wrap loiq-wp-agent-wrap">
            <h1>LOIQ WP Agent</h1>

            <?php if ($new_token): ?>
            <div class="loiq-card">
                <h2>Je Access Token</h2>
                <p><strong>Kopieer dit token nu!</strong> Het wordt niet meer getoond na het verlaten van deze pagina.</p>
                <div class="loiq-token-display loiq-token-new" id="new-token"><?php echo esc_html($new_token); ?></div>
                <button type="button" class="button button-primary" onclick="copyToken()">Kopieer Token</button>

                <h3 style="margin-top: 20px;">Terminal Prompt (copy-paste ready)</h3>
                <pre id="terminal-prompt" style="margin: 10px 0; padding: 15px; background: #1d2327; color: #50fa7b; font-family: monospace; font-size: 13px; border-radius: 4px; overflow-x: auto; cursor: pointer;" onclick="copyTerminal()">curl -s -H "X-Claude-Token: <?php echo esc_attr($new_token); ?>" <?php echo esc_url(rest_url('claude/v1/status')); ?> | python3 -m json.tool</pre>
                <button type="button" class="button" onclick="copyTerminal()">Kopieer Terminal Prompt</button>

                <h3 style="margin-top: 20px;">AI Dev Prompt (geef aan je developer)</h3>
                <pre id="ai-dev-prompt" style="margin: 10px 0; padding: 15px; background: #1a1a2e; color: #e0e0ff; font-family: monospace; font-size: 12px; border-radius: 4px; overflow-x: auto; white-space: pre-wrap; cursor: pointer;" onclick="copyAiPrompt()">Deze site heeft de LOIQ WP Agent plugin actief. Je kunt de site remote debuggen via REST API.

Base URL: <?php echo esc_url(rest_url('claude/v1/')); ?>

Header: X-Claude-Token: <?php echo esc_attr($new_token); ?>

Endpoints:
- /status    — WP/PHP versie, memory, debug mode
- /errors    — Laatste regels debug.log (?lines=50)
- /plugins   — Alle plugins met update status
- /theme     — Actief thema + parent info
- /database  — Tabellen en sizes (geen data)
- /code-context?topic=X — Code context (gravity-forms|woocommerce|divi|acf|custom-post-types|rest-api|cron|general)
- /styles    — CSS stylesheets, customizer CSS, theme CSS
- /forms     — Gravity Forms structuur (?id=3 voor detail)
- /page      — Pagina context (?url=/over-ons of ?id=42)

Voorbeeld:
curl -s -H "X-Claude-Token: <?php echo esc_attr($new_token); ?>" <?php echo esc_url(rest_url('claude/v1/status')); ?> | python3 -m json.tool

Token is tijdelijk actief. Alle endpoints zijn read-only.</pre>
                <button type="button" class="button button-primary" onclick="copyAiPrompt()">Kopieer AI Dev Prompt</button>
            </div>
            <?php delete_transient('loiq_agent_new_token'); ?>
            <?php endif; ?>

            <div class="loiq-card">
                <h2>Status</h2>
                <p>
                    <span class="loiq-status <?php echo $is_active ? 'loiq-status-active' : 'loiq-status-inactive'; ?>">
                        <?php echo $is_active ? 'Actief' : 'Uitgeschakeld'; ?>
                    </span>
                    <?php if ($is_active): ?>
                        &nbsp; tot <?php echo date_i18n('d-m-Y H:i', $enabled_until); ?>
                        (<?php echo human_time_diff(time(), $enabled_until); ?> resterend)
                    <?php endif; ?>
                </p>

                <p>
                    <?php if ($is_active): ?>
                        <button type="button" class="button loiq-btn" onclick="disableDebug()">Uitschakelen</button>
                    <?php endif; ?>
                    <button type="button" class="button loiq-btn" onclick="enableDebug(1)">Activeer 1 uur</button>
                    <button type="button" class="button loiq-btn" onclick="enableDebug(24)">Activeer 24 uur</button>
                    <button type="button" class="button loiq-btn" onclick="enableDebug(168)">Activeer 1 week</button>
                </p>

                <?php if ($mu_plugin_installed): ?>
                <div class="loiq-help" style="margin-top: 15px;">
                    <strong>Managed Debug Logging actief.</strong>
                    WP_DEBUG_LOG wordt automatisch aan/uit gezet met de timer hierboven.
                    <?php if ($is_active): ?>
                        Debug logging is nu <strong>AAN</strong>.
                    <?php else: ?>
                        Debug logging is nu <strong>UIT</strong>.
                    <?php endif; ?>
                    <br><small>Opt-out: voeg <code>define('LOIQ_AGENT_UNMANAGED', true);</code> toe aan wp-config.php</small>
                </div>
                <?php else: ?>
                <div class="loiq-help" style="margin-top: 15px; border-left-color: #dba617;">
                    <strong>Managed Debug Logging niet actief.</strong>
                    <button type="button" class="button button-small" onclick="installMuPlugin()">Installeer mu-plugin</button>
                    <br><small>Koppelt WP_DEBUG_LOG aan de timer zodat debug logging automatisch stopt.</small>
                </div>
                <?php endif; ?>
            </div>

            <div class="loiq-card">
                <h2>Token Beheer</h2>
                <p>
                    <button type="button" class="button" onclick="regenerateToken()">Regenereer Token</button>
                    <span class="description">Dit maakt het huidige token ongeldig.</span>
                </p>
            </div>

            <div class="loiq-card">
                <h2>Gebruik</h2>
                <div class="loiq-help">
                    <p><strong>Endpoint:</strong> <code><?php echo esc_url(rest_url('claude/v1/status')); ?></code></p>
                    <p><strong>Header:</strong> <code>X-Claude-Token: &lt;jouw-token&gt;</code></p>
                    <p><strong>Voorbeeld:</strong></p>
                    <pre style="margin: 10px 0; padding: 10px; background: #f0f0f1; overflow-x: auto;">curl -H "X-Claude-Token: TOKEN" <?php echo esc_url(rest_url('claude/v1/status')); ?></pre>
                </div>

                <h3>Read Endpoints (v1)</h3>
                <table class="loiq-table">
                    <tr><th>Endpoint</th><th>Beschrijving</th></tr>
                    <tr><td><code>GET /claude/v1/status</code></td><td>WP versie, PHP, memory, debug mode</td></tr>
                    <tr><td><code>GET /claude/v1/errors</code></td><td>Laatste regels debug.log (?lines=50)</td></tr>
                    <tr><td><code>GET /claude/v1/plugins</code></td><td>Plugins lijst met update status</td></tr>
                    <tr><td><code>GET /claude/v1/theme</code></td><td>Actief thema info</td></tr>
                    <tr><td><code>GET /claude/v1/database</code></td><td>Database tabellen info (geen data)</td></tr>
                    <tr><td><code>GET /claude/v1/code-context</code></td><td>Code context (?topic=gravity-forms|woocommerce|divi|acf|...)</td></tr>
                    <tr><td><code>GET /claude/v1/styles</code></td><td>CSS stylesheets, customizer CSS, theme CSS</td></tr>
                    <tr><td><code>GET /claude/v1/forms</code></td><td>Gravity Forms structuur (?id=3 voor detail)</td></tr>
                    <tr><td><code>GET /claude/v1/page</code></td><td>Pagina context (?url=/over-ons of ?id=42)</td></tr>
                </table>

                <h3>Write Endpoints (v2) — vereist Power Mode</h3>
                <table class="loiq-table">
                    <tr><th>Endpoint</th><th>Power Mode</th><th>Beschrijving</th></tr>
                    <tr><td><code>POST /claude/v2/css/deploy</code></td><td>css</td><td>CSS deployen naar child theme, Divi, of customizer</td></tr>
                    <tr><td><code>POST /claude/v2/option/update</code></td><td>options</td><td>Whitelisted WP opties bijwerken</td></tr>
                    <tr><td><code>POST /claude/v2/plugin/toggle</code></td><td>plugins</td><td>Plugin activeren/deactiveren</td></tr>
                    <tr><td><code>POST /claude/v2/content/update</code></td><td>content</td><td>Post/pagina content bijwerken</td></tr>
                    <tr><td><code>POST /claude/v2/snippet/deploy</code></td><td>snippets</td><td>PHP snippet deployen als mu-plugin</td></tr>
                    <tr><td><code>POST /claude/v2/rollback</code></td><td>&mdash;</td><td>Snapshot terugdraaien</td></tr>
                    <tr><td><code>GET /claude/v2/snapshots</code></td><td>&mdash;</td><td>Recente snapshots lijst</td></tr>
                    <tr><td><code>GET /claude/v2/power-modes</code></td><td>&mdash;</td><td>Huidige power mode status</td></tr>
                </table>

                <h3>Site Builder Endpoints (v3) — vereist Power Mode</h3>
                <table class="loiq-table">
                    <tr><th>Endpoint</th><th>Power Mode</th><th>Beschrijving</th></tr>
                    <tr><td><code>POST /claude/v3/page/create</code></td><td>content</td><td>Pagina aanmaken met Divi content of template</td></tr>
                    <tr><td><code>POST /claude/v3/page/clone</code></td><td>content</td><td>Pagina dupliceren als draft</td></tr>
                    <tr><td><code>GET /claude/v3/page/list</code></td><td>&mdash;</td><td>Pagina's lijst met status en Divi info</td></tr>
                    <tr><td><code>POST /claude/v3/divi/build</code></td><td>divi_builder</td><td>JSON → Divi shortcode</td></tr>
                    <tr><td><code>POST /claude/v3/divi/parse</code></td><td>&mdash;</td><td>Divi shortcode → JSON</td></tr>
                    <tr><td><code>POST /claude/v3/divi/validate</code></td><td>&mdash;</td><td>Shortcode structuur valideren</td></tr>
                    <tr><td><code>GET /claude/v3/divi/modules</code></td><td>&mdash;</td><td>Module registry</td></tr>
                    <tr><td><code>GET /claude/v3/divi/templates</code></td><td>&mdash;</td><td>Page template library</td></tr>
                    <tr><td><code>GET /claude/v3/theme-builder/list</code></td><td>&mdash;</td><td>Theme Builder templates</td></tr>
                    <tr><td><code>POST /claude/v3/theme-builder/create</code></td><td>divi_builder</td><td>Template aanmaken</td></tr>
                    <tr><td><code>POST /claude/v3/theme-builder/update</code></td><td>divi_builder</td><td>Template content updaten</td></tr>
                    <tr><td><code>POST /claude/v3/theme-builder/assign</code></td><td>divi_builder</td><td>Template condities toewijzen</td></tr>
                    <tr><td><code>GET /claude/v3/child-theme/status</code></td><td>&mdash;</td><td>Child theme status + bestanden</td></tr>
                    <tr><td><code>POST /claude/v3/child-theme/create</code></td><td>child_theme</td><td>Child theme scaffolden (style.css + functions.php)</td></tr>
                    <tr><td><code>POST /claude/v3/child-theme/functions/append</code></td><td>child_theme</td><td>Tagged block toevoegen aan functions.php</td></tr>
                    <tr><td><code>POST /claude/v3/child-theme/functions/remove</code></td><td>child_theme</td><td>Tagged block verwijderen</td></tr>
                    <tr><td><code>GET /claude/v3/child-theme/functions/list</code></td><td>&mdash;</td><td>Tagged blocks lijst</td></tr>
                    <tr><td><code>POST /claude/v3/menu/create</code></td><td>menus</td><td>Menu aanmaken</td></tr>
                    <tr><td><code>POST /claude/v3/menu/items/add</code></td><td>menus</td><td>Menu items toevoegen</td></tr>
                    <tr><td><code>POST /claude/v3/menu/assign</code></td><td>menus</td><td>Menu toewijzen aan locatie</td></tr>
                    <tr><td><code>POST /claude/v3/media/upload</code></td><td>media</td><td>Afbeelding uploaden (base64 of URL)</td></tr>
                    <tr><td><code>GET /claude/v3/media/search</code></td><td>&mdash;</td><td>Media library doorzoeken</td></tr>
                    <tr><td><code>POST /claude/v3/forms/create</code></td><td>forms</td><td>Gravity Forms formulier aanmaken</td></tr>
                    <tr><td><code>POST /claude/v3/forms/update</code></td><td>forms</td><td>Formulier bewerken</td></tr>
                    <tr><td><code>POST /claude/v3/facet/create</code></td><td>facets</td><td>FacetWP facet aanmaken</td></tr>
                    <tr><td><code>POST /claude/v3/taxonomy/create-term</code></td><td>content</td><td>Taxonomy term aanmaken</td></tr>
                    <tr><td><code>POST /claude/v3/taxonomy/assign</code></td><td>content</td><td>Terms toewijzen aan post</td></tr>
                </table>
            </div>

            <div class="loiq-card">
                <h2>IP Whitelist (optioneel)</h2>
                <p>Laat leeg om alle IPs toe te staan. Eén IP per regel.</p>
                <form method="post" action="options.php">
                    <?php settings_fields('loiq_agent_settings'); ?>
                    <textarea name="loiq_agent_ip_whitelist" rows="4" style="width: 100%; font-family: monospace;"><?php echo esc_textarea(get_option('loiq_agent_ip_whitelist', '')); ?></textarea>
                    <?php submit_button('Opslaan', 'secondary'); ?>
                </form>
            </div>

            <?php
            // v2.0: Power Modes
            $power_modes = LOIQ_Agent_Safeguards::get_power_modes();
            $mode_labels = [
                'css'          => ['CSS Deploy', 'CSS injecteren in child theme, Divi custom CSS, of customizer'],
                'options'      => ['Option Updates', 'Whitelisted WP opties bijwerken (blogname, timezone, etc.)'],
                'plugins'      => ['Plugin Toggle', 'Plugins activeren/deactiveren via API'],
                'content'      => ['Content Updates', 'Post/pagina titel, content, meta, pages en taxonomies bijwerken'],
                'snippets'     => ['Code Snippets', 'PHP snippets deployen als mu-plugin'],
                'divi_builder' => ['Divi Builder', 'Divi shortcodes bouwen, Theme Builder templates, Library items'],
                'child_theme'  => ['Child Theme', 'functions.php tagged blocks toevoegen/verwijderen'],
                'menus'        => ['Menu Management', 'WP menus aanmaken, items toevoegen, Max Mega Menu configuratie'],
                'media'        => ['Media Upload', 'Afbeeldingen uploaden naar media library (max 5MB)'],
                'forms'        => ['Gravity Forms', 'Formulieren aanmaken, bewerken en verwijderen via GFAPI'],
                'facets'       => ['FacetWP', 'Facets en templates aanmaken/bewerken'],
            ];
            ?>
            <div class="loiq-card">
                <h2>Power Modes (v3.0)</h2>
                <p>Per-categorie write permissions. Standaard alles uitgeschakeld (fail-closed).</p>
                <div class="loiq-power-modes">
                    <?php foreach ($mode_labels as $key => $info): ?>
                    <label>
                        <input type="checkbox" name="power_mode_<?php echo esc_attr($key); ?>"
                               <?php checked(!empty($power_modes[$key])); ?>
                               onchange="savePowerModes()">
                        <?php echo esc_html($info[0]); ?>
                        <span class="description"><?php echo esc_html($info[1]); ?></span>
                    </label>
                    <?php endforeach; ?>
                </div>
                <p style="margin-top: 10px;">
                    <button type="button" class="button" onclick="savePowerModes()">Opslaan</button>
                    <span class="description">Write rate limit: <?php echo LOIQ_Agent_Safeguards::WRITE_RATE_LIMIT_MINUTE; ?>/min, <?php echo LOIQ_Agent_Safeguards::WRITE_RATE_LIMIT_HOUR; ?>/uur</span>
                </p>
            </div>

            <?php
            // v2.0: Snapshots
            $snapshots = LOIQ_Agent_Safeguards::get_snapshots(10);
            ?>
            <div class="loiq-card">
                <h2>Recente Snapshots (v2.0)</h2>
                <?php if (empty($snapshots)): ?>
                    <p>Nog geen snapshots. Snapshots worden aangemaakt bij write operaties via de v2 API.</p>
                <?php else: ?>
                <table class="loiq-table">
                    <tr><th>ID</th><th>Type</th><th>Target</th><th>Status</th><th>Tijd</th><th>Actie</th></tr>
                    <?php foreach ($snapshots as $snap): ?>
                    <tr>
                        <td><?php echo esc_html($snap['id']); ?></td>
                        <td><code><?php echo esc_html($snap['action_type']); ?></code></td>
                        <td class="loiq-code"><?php echo esc_html(substr($snap['target_key'], 0, 40)); ?></td>
                        <td>
                            <?php if ($snap['rolled_back']): ?>
                                <span class="loiq-badge loiq-badge-rollback">Teruggedraaid</span>
                            <?php elseif ($snap['executed']): ?>
                                <span class="loiq-badge loiq-badge-executed">Uitgevoerd</span>
                            <?php else: ?>
                                <span class="loiq-badge loiq-badge-dryrun">Dry-run</span>
                            <?php endif; ?>
                        </td>
                        <td><?php echo esc_html($snap['created_at']); ?></td>
                        <td class="loiq-snapshot-actions">
                            <?php if ($snap['executed'] && !$snap['rolled_back']): ?>
                                <button type="button" class="button button-small" onclick="rollbackSnapshot(<?php echo esc_attr($snap['id']); ?>)">Rollback</button>
                            <?php else: ?>
                                &mdash;
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>

            <?php
            // v2.0: Deployed Snippets
            $deployed_snippets = LOIQ_Agent_Safeguards::get_deployed_snippets();
            ?>
            <div class="loiq-card">
                <h2>Gedeployde Snippets (v2.0)</h2>
                <?php if (empty($deployed_snippets)): ?>
                    <p>Geen actieve snippets. Deploy via <code>POST /claude/v2/snippet/deploy</code>.</p>
                <?php else: ?>
                <table class="loiq-table">
                    <tr><th>Naam</th><th>Bestand</th><th>Grootte</th><th>Laatst gewijzigd</th><th>Actie</th></tr>
                    <?php foreach ($deployed_snippets as $snippet): ?>
                    <tr>
                        <td><strong><?php echo esc_html($snippet['name']); ?></strong></td>
                        <td class="loiq-code"><?php echo esc_html($snippet['file']); ?></td>
                        <td><?php echo esc_html(size_format($snippet['size'])); ?></td>
                        <td><?php echo esc_html($snippet['modified']); ?></td>
                        <td>
                            <button type="button" class="button button-small" style="color:#721c24;" onclick="removeSnippet('<?php echo esc_js($snippet['name']); ?>')">Verwijderen</button>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <p><small><?php echo count($deployed_snippets); ?>/<?php echo LOIQ_Agent_Safeguards::SNIPPET_MAX_ACTIVE; ?> slots gebruikt</small></p>
                <?php endif; ?>
            </div>

            <?php if (!empty($recent_requests)): ?>
            <div class="loiq-card">
                <h2>Request Log (laatste 20)</h2>
                <p><button type="button" class="button" onclick="clearLog()">Log Wissen</button></p>
                <table class="loiq-table">
                    <tr><th>Tijd</th><th>Endpoint</th><th>IP</th><th>Status</th></tr>
                    <?php foreach ($recent_requests as $req): ?>
                    <tr>
                        <td><?php echo esc_html($req->created_at); ?></td>
                        <td><code><?php echo esc_html($req->endpoint); ?></code></td>
                        <td class="loiq-code"><?php echo esc_html($req->ip_address); ?></td>
                        <td class="loiq-log-<?php echo esc_attr($req->response_code); ?>"><?php echo esc_html($req->response_code); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
            <?php endif; ?>

            <div class="loiq-card">
                <h2>Security Features</h2>
                <ul>
                    <li>Token verificatie (password_hash)</li>
                    <li>HTTPS verplicht (behalve localhost)</li>
                    <li>Read rate limiting: <?php echo self::RATE_LIMIT_MINUTE; ?>/min, <?php echo self::RATE_LIMIT_HOUR; ?>/uur</li>
                    <li>Write rate limiting: <?php echo LOIQ_Agent_Safeguards::WRITE_RATE_LIMIT_MINUTE; ?>/min, <?php echo LOIQ_Agent_Safeguards::WRITE_RATE_LIMIT_HOUR; ?>/uur</li>
                    <li>Auto-disable timer (endpoints + debug logging + power modes)</li>
                    <li>IP whitelist (optioneel)</li>
                    <li>Request logging met GDPR IP anonimisatie</li>
                    <li>Per-categorie power modes (fail-closed)</li>
                    <li>Pre-edit snapshots met rollback</li>
                    <li>Dry-run mode voor alle write endpoints</li>
                    <li>Option whitelist (deny-by-default)</li>
                    <li>Snippet veiligheidsscanner (blokkeert eval, exec, etc.)</li>
                </ul>
            </div>
        </div>

        <script>
        function copyToken() {
            var token = document.getElementById('new-token').textContent.replace('NIEUW - Kopieer nu! ', '');
            navigator.clipboard.writeText(token).then(function() {
                alert('Token gekopieerd!');
            });
        }

        function copyTerminal() {
            var prompt = document.getElementById('terminal-prompt').textContent;
            navigator.clipboard.writeText(prompt).then(function() {
                alert('Terminal prompt gekopieerd!');
            });
        }

        function copyAiPrompt() {
            var prompt = document.getElementById('ai-dev-prompt').textContent;
            navigator.clipboard.writeText(prompt).then(function() {
                alert('AI Dev prompt gekopieerd! Geef aan je developer.');
            });
        }

        function regenerateToken() {
            if (!confirm('Weet je zeker dat je een nieuw token wilt genereren? Het huidige token wordt ongeldig.')) return;

            jQuery.post(ajaxurl, {
                action: 'loiq_agent_regenerate_token',
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function enableDebug(hours) {
            jQuery.post(ajaxurl, {
                action: 'loiq_agent_enable',
                hours: hours,
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function disableDebug() {
            jQuery.post(ajaxurl, {
                action: 'loiq_agent_disable',
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function clearLog() {
            if (!confirm('Weet je zeker dat je de log wilt wissen?')) return;

            jQuery.post(ajaxurl, {
                action: 'loiq_agent_clear_log',
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function installMuPlugin() {
            jQuery.post(ajaxurl, {
                action: 'loiq_agent_install_mu',
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function savePowerModes() {
            var modes = {};
            <?php foreach (array_keys($mode_labels) as $key): ?>
            modes['<?php echo esc_js($key); ?>'] = document.querySelector('input[name="power_mode_<?php echo esc_js($key); ?>"]').checked ? 1 : 0;
            <?php endforeach; ?>

            jQuery.post(ajaxurl, {
                action: 'loiq_agent_save_power_modes',
                modes: modes,
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function rollbackSnapshot(id) {
            if (!confirm('Snapshot #' + id + ' terugdraaien? De vorige staat wordt hersteld.')) return;

            jQuery.post(ajaxurl, {
                action: 'loiq_agent_rollback',
                snapshot_id: id,
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    alert('Snapshot #' + id + ' teruggedraaid.');
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function removeSnippet(name) {
            if (!confirm('Snippet "' + name + '" verwijderen? Dit kan de site beinvloeden.')) return;

            jQuery.post(ajaxurl, {
                action: 'loiq_agent_remove_snippet',
                name: name,
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }
        </script>
        <?php
    }

    // =========================================================================
    // AJAX HANDLERS
    // =========================================================================

    /**
     * Regenerate token
     */
    public function ajax_regenerate_token() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $token = bin2hex(random_bytes(32));
        update_option('loiq_agent_token_hash', password_hash($token, PASSWORD_DEFAULT));
        set_transient('loiq_agent_new_token', $token, 300);

        wp_send_json_success();
    }

    /**
     * Enable debug for X hours
     */
    public function ajax_enable() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $hours = absint(sanitize_text_field($_POST['hours'] ?? self::DEFAULT_HOURS));
        $hours = max(1, min(168, $hours)); // 1 hour to 1 week

        update_option('loiq_agent_enabled_until', time() + ($hours * 3600));

        wp_send_json_success();
    }

    /**
     * Disable debug
     */
    public function ajax_disable() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        update_option('loiq_agent_enabled_until', 0);

        wp_send_json_success();
    }

    /**
     * Clear request log
     */
    public function ajax_clear_log() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        global $wpdb;
        $wpdb->query($wpdb->prepare("TRUNCATE TABLE {$wpdb->prefix}loiq_agent_log"));

        wp_send_json_success();
    }

    /**
     * Install mu-plugin for managed debug logging
     */
    public function ajax_install_mu() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $result = self::install_mu_plugin();
        if ($result === true) {
            wp_send_json_success();
        } else {
            wp_send_json_error($result);
        }
    }

    // =========================================================================
    // v2.0 AJAX HANDLERS
    // =========================================================================

    /**
     * Save power modes from admin UI
     */
    public function ajax_save_power_modes() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $modes = isset($_POST['modes']) && is_array($_POST['modes']) ? $_POST['modes'] : [];
        $clean = [];
        foreach (['css', 'options', 'plugins', 'content', 'snippets', 'divi_builder', 'child_theme', 'menus', 'media', 'forms', 'facets'] as $key) {
            $clean[$key] = !empty($modes[$key]);
        }

        LOIQ_Agent_Safeguards::set_power_modes($clean);
        wp_send_json_success();
    }

    /**
     * Rollback a snapshot from admin UI
     */
    public function ajax_rollback() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $snapshot_id = absint($_POST['snapshot_id'] ?? 0);
        if ($snapshot_id <= 0) {
            wp_send_json_error('Ongeldig snapshot ID');
        }

        $result = LOIQ_Agent_Safeguards::rollback_snapshot($snapshot_id);
        if (is_wp_error($result)) {
            wp_send_json_error($result->get_error_message());
        }

        wp_send_json_success($result);
    }

    /**
     * Remove a deployed snippet from admin UI
     */
    public function ajax_remove_snippet() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $name = sanitize_file_name($_POST['name'] ?? '');
        if (empty($name)) {
            wp_send_json_error('Snippet naam ontbreekt');
        }

        $result = LOIQ_Agent_Safeguards::remove_snippet($name);
        if (is_wp_error($result)) {
            wp_send_json_error($result->get_error_message());
        }

        wp_send_json_success();
    }
}

/**
 * GitHub Auto-Updater
 */
class LOIQ_WP_Agent_Updater {

    private $plugin_file;
    private $plugin_slug;
    private $repo;
    private $cache_key = 'loiq_agent_update_check';
    private $cache_expiry = 43200; // 12 hours

    public function __construct() {
        $this->plugin_file = plugin_basename(LOIQ_AGENT_PATH . 'loiq-wp-agent.php');
        $this->plugin_slug = dirname($this->plugin_file);
        $this->repo = LOIQ_AGENT_GITHUB_REPO;

        // Hook into WP update system
        add_filter('pre_set_site_transient_update_plugins', [$this, 'check_for_update']);
        add_filter('plugins_api', [$this, 'plugin_info'], 10, 3);
        add_filter('upgrader_source_selection', [$this, 'fix_source_dir'], 10, 4);

        // Add "Check for updates" link on plugins page
        add_filter('plugin_action_links_' . $this->plugin_file, [$this, 'add_check_update_link']);
        add_action('admin_init', [$this, 'handle_check_update']);
        add_action('admin_notices', [$this, 'show_update_notice']);
    }

    /**
     * Check GitHub for new release
     */
    public function check_for_update($transient) {
        if (empty($transient->checked)) {
            return $transient;
        }

        $remote = $this->get_remote_version();

        if ($remote && version_compare(LOIQ_AGENT_VERSION, $remote['version'], '<')) {
            $transient->response[$this->plugin_file] = (object) [
                'slug'        => $this->plugin_slug,
                'plugin'      => $this->plugin_file,
                'new_version' => $remote['version'],
                'url'         => "https://github.com/{$this->repo}",
                'package'     => $remote['download_url'],
                'icons'       => [],
                'banners'     => [],
                'tested'      => get_bloginfo('version'),
                'requires_php'=> '7.4',
            ];
        }

        return $transient;
    }

    /**
     * Provide plugin info for the update modal
     */
    public function plugin_info($result, $action, $args) {
        if ($action !== 'plugin_information' || ($args->slug ?? '') !== $this->plugin_slug) {
            return $result;
        }

        $remote = $this->get_remote_version();

        if (!$remote) {
            return $result;
        }

        return (object) [
            'name'            => 'LOIQ WP Agent',
            'slug'            => $this->plugin_slug,
            'version'         => $remote['version'],
            'author'          => '<a href="https://loiq.nl">LOIQ</a>',
            'author_profile'  => 'https://loiq.nl',
            'homepage'        => "https://github.com/{$this->repo}",
            'requires'        => '5.8',
            'requires_php'    => '7.4',
            'tested'          => get_bloginfo('version'),
            'download_link'   => $remote['download_url'],
            'sections'        => [
                'description'  => 'Beveiligde REST API endpoints voor Claude CLI site debugging.',
                'changelog'    => $remote['changelog'] ?? 'Zie GitHub releases voor changelog.',
            ],
        ];
    }

    /**
     * Fix folder name after unzip (GitHub adds -tag suffix)
     */
    public function fix_source_dir($source, $remote_source, $upgrader, $hook_extra) {
        if (!isset($hook_extra['plugin']) || $hook_extra['plugin'] !== $this->plugin_file) {
            return $source;
        }

        global $wp_filesystem;

        $new_source = trailingslashit($remote_source) . $this->plugin_slug . '/';

        if ($source !== $new_source && $wp_filesystem->move($source, $new_source)) {
            return $new_source;
        }

        return $source;
    }

    /**
     * Show admin notice after update check
     */
    public function show_update_notice() {
        $message = get_transient('loiq_update_notice');
        if (!$message) return;
        delete_transient('loiq_update_notice');
        $type = strpos($message, 'up-to-date') !== false ? 'info' : 'warning';
        echo '<div class="notice notice-' . $type . ' is-dismissible"><p><strong>' . esc_html($message) . '</strong></p></div>';
    }

    /**
     * Add "Check for updates" action link on the plugins page
     */
    public function add_check_update_link($links) {
        $check_url = wp_nonce_url(
            admin_url('plugins.php?loiq_check_update=1'),
            'loiq_check_update'
        );
        $links['check_update'] = '<a href="' . esc_url($check_url) . '">Check for updates</a>';
        return $links;
    }

    /**
     * Handle the "Check for updates" click — clear cache, force re-check
     */
    public function handle_check_update() {
        if (empty($_GET['loiq_check_update']) || !current_user_can('update_plugins')) {
            return;
        }

        check_admin_referer('loiq_check_update');

        // Clear our cache
        delete_transient($this->cache_key);

        // Force WordPress to re-check plugin updates
        delete_site_transient('update_plugins');
        wp_update_plugins();

        // Check if an update was found
        $remote = $this->get_remote_version();
        if ($remote && version_compare(LOIQ_AGENT_VERSION, $remote['version'], '<')) {
            $message = 'LOIQ WP Agent update gevonden: v' . $remote['version'];
        } else {
            $message = 'LOIQ WP Agent is up-to-date (v' . LOIQ_AGENT_VERSION . ')';
        }

        // Redirect back with admin notice
        set_transient('loiq_update_notice', $message, 30);
        wp_safe_redirect(admin_url('plugins.php'));
        exit;
    }

    /**
     * Get latest release info from GitHub
     */
    private function get_remote_version() {
        // Check cache first
        $cached = get_transient($this->cache_key);
        if ($cached !== false) {
            return $cached;
        }

        // Fetch from GitHub API
        $response = wp_remote_get(
            "https://api.github.com/repos/{$this->repo}/releases/latest",
            [
                'timeout' => 10,
                'headers' => [
                    'Accept' => 'application/vnd.github.v3+json',
                    'User-Agent' => 'WordPress/' . get_bloginfo('version'),
                ],
            ]
        );

        if (is_wp_error($response) || wp_remote_retrieve_response_code($response) !== 200) {
            return null;
        }

        $release = json_decode(wp_remote_retrieve_body($response), true);

        if (empty($release['tag_name'])) {
            return null;
        }

        // Remove 'v' prefix from version tag
        $version = ltrim($release['tag_name'], 'v');

        // Find zip asset or use zipball_url
        $download_url = $release['zipball_url'];
        foreach ($release['assets'] ?? [] as $asset) {
            if (substr($asset['name'], -4) === '.zip') {
                $download_url = $asset['browser_download_url'];
                break;
            }
        }

        $data = [
            'version'      => $version,
            'download_url' => $download_url,
            'changelog'    => $release['body'] ?? '',
            'published_at' => $release['published_at'] ?? '',
        ];

        // Cache result
        set_transient($this->cache_key, $data, $this->cache_expiry);

        return $data;
    }
}

// Initialize updater
new LOIQ_WP_Agent_Updater();

// Register settings
add_action('admin_init', function() {
    register_setting('loiq_agent_settings', 'loiq_agent_ip_whitelist', [
        'type' => 'string',
        'sanitize_callback' => 'sanitize_textarea_field',
    ]);

});

// Initialize
register_activation_hook(__FILE__, ['LOIQ_WP_Agent', 'on_activation']);
register_deactivation_hook(__FILE__, ['LOIQ_WP_Agent', 'on_deactivation']);
add_action('plugins_loaded', ['LOIQ_WP_Agent', 'get_instance']);
