<?php
/**
 * Plugin Name: LOIQ WordPress Agent
 * Description: Beveiligde REST API endpoints voor Claude CLI site debugging + write capabilities met safeguards.
 * Version: 3.1.1
 * Update URI: https://github.com/LOIQ-ai/loiq-wp-assistent
 * Author: LOIQ
 * Author URI: https://loiq.nl
 * License: GPL v2 or later
 * Requires PHP: 7.4
 */

if (!defined('ABSPATH')) exit;

define('LOIQ_AGENT_VERSION', '3.1.1');
define('LOIQ_AGENT_DB_VERSION', '2.0.0');
define('LOIQ_AGENT_GITHUB_REPO', 'LOIQ-ai/loiq-wp-assistent');
define('LOIQ_AGENT_PATH', plugin_dir_path(__FILE__));

// Load v1.0 read endpoints
require_once LOIQ_AGENT_PATH . 'includes/class-read-endpoints.php';

// Load v2.0 includes
require_once LOIQ_AGENT_PATH . 'includes/class-safeguards.php';
require_once LOIQ_AGENT_PATH . 'includes/class-audit.php';
require_once LOIQ_AGENT_PATH . 'includes/class-write-endpoints.php';

// Load v3.0 includes
require_once LOIQ_AGENT_PATH . 'includes/class-divi-builder.php';
require_once LOIQ_AGENT_PATH . 'includes/class-divi-theme-builder.php';
require_once LOIQ_AGENT_PATH . 'includes/class-page-endpoints.php';
require_once LOIQ_AGENT_PATH . 'includes/class-child-theme.php';
require_once LOIQ_AGENT_PATH . 'includes/class-menu-endpoints.php';
require_once LOIQ_AGENT_PATH . 'includes/class-media-endpoints.php';
require_once LOIQ_AGENT_PATH . 'includes/class-forms-endpoints.php';
require_once LOIQ_AGENT_PATH . 'includes/class-facet-endpoints.php';
require_once LOIQ_AGENT_PATH . 'includes/class-taxonomy-endpoints.php';

/**
 * Main Plugin Class
 */
class LOIQ_WP_Agent {

    private static $instance = null;

    // Rate limits
    const RATE_LIMIT_MINUTE = 60;
    const RATE_LIMIT_HOUR = 1000;

    // Default auto-disable hours
    const DEFAULT_HOURS = 24;

    // mu-plugin filename
    const MU_PLUGIN_FILE = 'loiq-agent-logging.php';

    public static function get_instance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Plugin activation - generate token and create tables
     */
    public static function on_activation() {
        // Generate secure token
        $token = bin2hex(random_bytes(32));

        // Store hashed token (never store plain text)
        update_option('loiq_agent_token_hash', password_hash($token, PASSWORD_DEFAULT));

        // Store plain token temporarily for one-time display
        set_transient('loiq_agent_new_token', $token, 300); // 5 minutes

        // Enable for default hours
        update_option('loiq_agent_enabled_until', time() + (self::DEFAULT_HOURS * 3600));

        // Create log table
        self::create_tables();

        // Install mu-plugin for managed debug logging
        self::install_mu_plugin();

        // Redirect to settings page to show token
        set_transient('loiq_agent_activation_redirect', true, 30);
    }

    /**
     * Plugin deactivation
     */
    public static function on_deactivation() {
        // Clear transients
        delete_transient('loiq_agent_new_token');
        delete_transient('loiq_agent_activation_redirect');

        // Remove mu-plugin
        self::remove_mu_plugin();

        // Clear scheduled cron events
        wp_clear_scheduled_hook('loiq_agent_prune_snapshots');
    }

    /**
     * Install mu-plugin that manages WP_DEBUG_LOG via our timer.
     * Returns true on success, error message on failure.
     */
    public static function install_mu_plugin() {
        $mu_dir = ABSPATH . 'wp-content/mu-plugins';
        $mu_file = $mu_dir . '/' . self::MU_PLUGIN_FILE;

        // Create mu-plugins dir if needed
        if (!is_dir($mu_dir)) {
            if (!wp_mkdir_p($mu_dir)) {
                return 'Kan mu-plugins directory niet aanmaken';
            }
        }

        $content = <<<'MUPHP'
<?php
/**
 * LOIQ WP Agent - Managed Debug Logging
 * Version: %%VERSION%%
 *
 * Enables PHP error logging when the LOIQ WP Agent timer is active.
 * Disables logging when the timer expires. No wp-config.php editing needed.
 *
 * @generated by LOIQ WP Agent plugin — do not edit
 */
if (!defined('ABSPATH')) exit;

// Escape hatch: define('LOIQ_AGENT_UNMANAGED', true) in wp-config.php
if (defined('LOIQ_AGENT_UNMANAGED') && LOIQ_AGENT_UNMANAGED) {
    return;
}

$loiq_timer = (int) get_option('loiq_agent_enabled_until', 0);
$loiq_active = ($loiq_timer > 0 && time() < $loiq_timer);

if ($loiq_active) {
    // Timer actief: enable debug logging
    error_reporting(E_ALL);
    @ini_set('log_errors', '1');
    @ini_set('error_log', WP_CONTENT_DIR . '/debug.log');
    @ini_set('display_errors', '0');

    if (!defined('WP_DEBUG'))         define('WP_DEBUG', true);
    if (!defined('WP_DEBUG_LOG'))     define('WP_DEBUG_LOG', true);
    if (!defined('WP_DEBUG_DISPLAY')) define('WP_DEBUG_DISPLAY', false);
} else {
    // Timer verlopen: disable debug logging
    @ini_set('log_errors', '0');
    @ini_set('display_errors', '0');

    if (!defined('WP_DEBUG'))         define('WP_DEBUG', false);
    if (!defined('WP_DEBUG_LOG'))     define('WP_DEBUG_LOG', false);
    if (!defined('WP_DEBUG_DISPLAY')) define('WP_DEBUG_DISPLAY', false);
}
MUPHP;

        // Inject version (nowdoc doesn't interpolate)
        $content = str_replace('%%VERSION%%', LOIQ_AGENT_VERSION, $content);

        if (file_put_contents($mu_file, $content) === false) {
            return 'Kan mu-plugin niet schrijven naar ' . $mu_file;
        }

        return true;
    }

    /**
     * Remove the mu-plugin file.
     */
    public static function remove_mu_plugin() {
        $mu_file = ABSPATH . 'wp-content/mu-plugins/' . self::MU_PLUGIN_FILE;
        if (file_exists($mu_file)) {
            @unlink($mu_file);
        }
    }

    /**
     * Install or update mu-plugin if missing or outdated.
     * Runs on every load so updates via WP auto-updater are picked up.
     */
    private function maybe_update_mu_plugin() {
        $mu_file = ABSPATH . 'wp-content/mu-plugins/' . self::MU_PLUGIN_FILE;

        // Check if mu-plugin exists and contains current version
        if (file_exists($mu_file)) {
            $content = file_get_contents($mu_file);
            if (strpos($content, LOIQ_AGENT_VERSION) !== false) {
                return; // Up to date
            }
        }

        // Missing or outdated — (re)install
        self::install_mu_plugin();
    }

    /**
     * Create database tables
     */
    private static function create_tables() {
        global $wpdb;
        $charset = $wpdb->get_charset_collate();

        $log_table = $wpdb->prefix . 'loiq_agent_log';
        $sql_log = "CREATE TABLE $log_table (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            endpoint VARCHAR(100) NOT NULL,
            ip_address VARCHAR(45) NOT NULL,
            response_code SMALLINT NOT NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY endpoint (endpoint),
            KEY created_at (created_at)
        ) $charset;";

        $snapshot_table = $wpdb->prefix . 'loiq_agent_snapshots';
        $sql_snapshots = "CREATE TABLE $snapshot_table (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            action_type VARCHAR(50) NOT NULL,
            target_key VARCHAR(255) NOT NULL,
            before_value LONGTEXT,
            after_value LONGTEXT,
            executed TINYINT(1) DEFAULT 0,
            rolled_back TINYINT(1) DEFAULT 0,
            session_id VARCHAR(64),
            ip_address VARCHAR(45),
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY action_type (action_type),
            KEY created_at (created_at),
            KEY session_id (session_id)
        ) $charset;";

        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        dbDelta($sql_log);
        dbDelta($sql_snapshots);

        update_option('loiq_agent_db_version', LOIQ_AGENT_DB_VERSION);
    }

    // Allowed email domains for admin visibility
    const ALLOWED_EMAIL_DOMAINS = ['ultrax.agency', 'teamultrax.nl', 'teamultrax.com'];

    private function __construct() {
        // Ensure mu-plugin is installed and current after updates
        $this->maybe_update_mu_plugin();

        // DB upgrade check (for updates without re-activation)
        $this->maybe_upgrade_db();

        // Activation redirect
        add_action('admin_init', [$this, 'activation_redirect']);

        // Register REST routes (v1 + v2 + v3) — token-based, no email restriction
        add_action('rest_api_init', [$this, 'register_routes']);

        // Admin menu (email-gated in callback)
        add_action('admin_menu', [$this, 'add_admin_menu']);

        // Admin assets
        add_action('admin_enqueue_scripts', [$this, 'enqueue_admin_assets']);

        // AJAX handlers (existing)
        add_action('wp_ajax_loiq_agent_regenerate_token', [$this, 'ajax_regenerate_token']);
        add_action('wp_ajax_loiq_agent_enable', [$this, 'ajax_enable']);
        add_action('wp_ajax_loiq_agent_disable', [$this, 'ajax_disable']);
        add_action('wp_ajax_loiq_agent_clear_log', [$this, 'ajax_clear_log']);
        add_action('wp_ajax_loiq_agent_install_mu', [$this, 'ajax_install_mu']);

        // AJAX handlers (v2.0)
        add_action('wp_ajax_loiq_agent_save_power_modes', [$this, 'ajax_save_power_modes']);
        add_action('wp_ajax_loiq_agent_rollback', [$this, 'ajax_rollback']);
        add_action('wp_ajax_loiq_agent_remove_snippet', [$this, 'ajax_remove_snippet']);

        // Hide plugin from plugins list for non-allowed users
        add_filter('all_plugins', [$this, 'filter_plugin_visibility']);

        // Snapshot retention: prune >30 days daily
        add_action('loiq_agent_prune_snapshots', [__CLASS__, 'cron_prune_snapshots']);
        if (!wp_next_scheduled('loiq_agent_prune_snapshots')) {
            wp_schedule_event(time(), 'daily', 'loiq_agent_prune_snapshots');
        }
    }

    /**
     * WP Cron callback: prune old snapshots.
     * @since 3.1.0
     */
    public static function cron_prune_snapshots() {
        LOIQ_Agent_Safeguards::prune_snapshots(30);
    }

    /**
     * Upgrade DB tables if version mismatch
     */
    private function maybe_upgrade_db() {
        $installed = get_option('loiq_agent_db_version', '0');
        if (version_compare($installed, LOIQ_AGENT_DB_VERSION, '<')) {
            self::create_tables();
        }
    }

    /**
     * Redirect to settings after activation
     */
    public function activation_redirect() {
        if (get_transient('loiq_agent_activation_redirect') && self::is_allowed_admin_user()) {
            delete_transient('loiq_agent_activation_redirect');
            wp_redirect(admin_url('tools.php?page=loiq-wp-agent'));
            exit;
        }
    }

    /**
     * Register REST API routes
     */
    public function register_routes() {
        // Register v1 read endpoints
        LOIQ_Agent_Read_Endpoints::register_routes($this);

        // Register v2 write + management endpoints
        LOIQ_Agent_Write_Endpoints::register_routes($this);

        // Register v3 site builder endpoints
        LOIQ_Agent_Divi_Builder::register_routes($this);
        LOIQ_Agent_Divi_Theme_Builder::register_routes($this);
        LOIQ_Agent_Page_Endpoints::register_routes($this);
        LOIQ_Agent_Child_Theme::register_routes($this);
        LOIQ_Agent_Menu_Endpoints::register_routes($this);
        LOIQ_Agent_Media_Endpoints::register_routes($this);
        LOIQ_Agent_Forms_Endpoints::register_routes($this);
        LOIQ_Agent_Facet_Endpoints::register_routes($this);
        LOIQ_Agent_Taxonomy_Endpoints::register_routes($this);
    }

    /**
     * Permission callback for v2 write endpoints.
     * Extends check_permission with power mode + stricter rate limits.
     */
    public function check_write_permission(WP_REST_Request $request) {
        // 1. All base checks (HTTPS, timer, token, IP, read rate limit)
        $base_check = $this->check_permission($request);
        if (is_wp_error($base_check)) return $base_check;

        // 2. Power mode check for this action category
        $category = $this->get_write_category($request);
        if ($category && !LOIQ_Agent_Safeguards::is_enabled($category)) {
            return new WP_Error('power_mode_off',
                "Power mode voor '{$category}' is uitgeschakeld. Enable via wp-admin.",
                ['status' => 403]
            );
        }

        // 3. Stricter rate limit for writes
        $client_ip = $this->get_client_ip();
        $write_limit = LOIQ_Agent_Safeguards::check_write_rate_limit($client_ip);
        if (is_wp_error($write_limit)) return $write_limit;

        return true;
    }

    /**
     * Determine the power mode category from a write request route.
     *
     * @param WP_REST_Request $request
     * @return string|null
     */
    private function get_write_category(WP_REST_Request $request) {
        $route = $request->get_route();

        // v2 routes
        if (strpos($route, '/css/') !== false) return 'css';
        if (strpos($route, '/option/') !== false) return 'options';
        if (strpos($route, '/plugin/') !== false) return 'plugins';
        if (strpos($route, '/content/') !== false) return 'content';
        if (strpos($route, '/snippet/') !== false) return 'snippets';

        // v3 routes
        if (strpos($route, '/divi/build') !== false) return 'divi_builder';
        if (strpos($route, '/divi/library/save') !== false) return 'divi_builder';
        if (strpos($route, '/theme-builder/') !== false) return 'divi_builder';
        if (strpos($route, '/child-theme/') !== false) return 'child_theme';
        if (strpos($route, '/menu/') !== false) return 'menus';
        if (strpos($route, '/media/upload') !== false) return 'media';
        if (strpos($route, '/forms/') !== false) return 'forms';
        if (strpos($route, '/facet/') !== false) return 'facets';
        if (strpos($route, '/page/create') !== false) return 'content';
        if (strpos($route, '/page/clone') !== false) return 'content';
        if (strpos($route, '/taxonomy/create-term') !== false) return 'content';
        if (strpos($route, '/taxonomy/assign') !== false) return 'content';

        // Rollback: check the snapshot's action type
        if (strpos($route, '/rollback') !== false) return null; // Allow rollback regardless

        return null;
    }

    /**
     * Security permission callback - ALL checks here
     */
    public function check_permission(WP_REST_Request $request) {
        // 1. HTTPS check (allow localhost for dev)
        $is_localhost = in_array(sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'] ?? '')), ['127.0.0.1', '::1']);
        if (!is_ssl() && !$is_localhost) {
            $this->log_request($request->get_route(), 403, 'https_required');
            return new WP_Error('https_required', 'HTTPS is verplicht', ['status' => 403]);
        }

        // 2. Auto-disable check
        $enabled_until = (int) get_option('loiq_agent_enabled_until', 0);
        if ($enabled_until > 0 && time() > $enabled_until) {
            $this->log_request($request->get_route(), 503, 'timer_expired');
            return new WP_Error('disabled', 'Debug endpoint is uitgeschakeld (timer verlopen)', ['status' => 503]);
        }

        // 3. Auth lockout check — block IP after 5 failed attempts (15 min cooldown)
        $client_ip_for_lockout = sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'] ?? '0.0.0.0'));
        $lockout_key = 'loiq_agent_lockout_' . md5($client_ip_for_lockout);
        $failed_attempts = (int) get_transient($lockout_key);
        if ($failed_attempts >= 5) {
            $this->log_request($request->get_route(), 403, 'auth_lockout:' . $failed_attempts);
            return new WP_Error('auth_lockout', 'Te veel mislukte pogingen. Probeer over 15 minuten opnieuw.', ['status' => 403]);
        }

        // 4. Token verification (primary) OR WP Application Password (fallback)
        $token = $request->get_header('X-Claude-Token');
        $authenticated = false;

        if (!empty($token)) {
            // Primary auth: LOIQ token
            $hash = get_option('loiq_agent_token_hash', '');
            if (empty($hash) || !password_verify($token, $hash)) {
                set_transient($lockout_key, $failed_attempts + 1, 900);
                $this->log_request($request->get_route(), 401, 'invalid_token');
                return new WP_Error('invalid_token', 'Ongeldig token', ['status' => 401]);
            }
            $authenticated = true;
        } else {
            // Fallback auth: WP Application Password (requires manage_options)
            $user = wp_get_current_user();
            if ($user->ID > 0 && user_can($user, 'manage_options')) {
                $authenticated = true;
            }
        }

        if (!$authenticated) {
            set_transient($lockout_key, $failed_attempts + 1, 900);
            $this->log_request($request->get_route(), 401, 'missing_token');
            return new WP_Error('missing_token', 'X-Claude-Token header of geldige WP authenticatie vereist', ['status' => 401]);
        }

        // Reset lockout on successful auth
        delete_transient($lockout_key);

        // 4. IP whitelist (if configured)
        $whitelist = get_option('loiq_agent_ip_whitelist', '');
        if (!empty($whitelist)) {
            $allowed_ips = array_map('trim', explode("\n", $whitelist));
            $client_ip = $this->get_client_ip();
            if (!in_array($client_ip, $allowed_ips)) {
                $this->log_request($request->get_route(), 403, 'ip_blocked');
                return new WP_Error('ip_blocked', 'IP niet toegestaan', ['status' => 403]);
            }
        }

        // 5. Rate limiting
        $client_ip = $this->get_client_ip();
        $ip_hash = md5($client_ip);

        // Per minute
        $minute_key = 'loiq_agent_rate_m_' . $ip_hash;
        $minute_count = (int) get_transient($minute_key);
        if ($minute_count >= self::RATE_LIMIT_MINUTE) {
            $this->log_request($request->get_route(), 429, 'rate_limit_minute');
            return new WP_Error('rate_limit', 'Te veel requests (max ' . self::RATE_LIMIT_MINUTE . '/min)', ['status' => 429]);
        }

        // Per hour
        $hour_key = 'loiq_agent_rate_h_' . $ip_hash;
        $hour_count = (int) get_transient($hour_key);
        if ($hour_count >= self::RATE_LIMIT_HOUR) {
            $this->log_request($request->get_route(), 429, 'rate_limit_hour');
            return new WP_Error('rate_limit', 'Te veel requests (max ' . self::RATE_LIMIT_HOUR . '/uur)', ['status' => 429]);
        }

        // Increment counters
        set_transient($minute_key, $minute_count + 1, 60);
        set_transient($hour_key, $hour_count + 1, 3600);

        // Log successful request
        $this->log_request($request->get_route(), 200);

        return true;
    }

    /**
     * Get client IP — secure against header spoofing.
     *
     * Only trusts REMOTE_ADDR by default. Proxy headers (CF, X-Forwarded-For)
     * are only used when trusted_proxy_ip is configured in admin, AND the
     * request actually comes from that proxy IP.
     */
    private function get_client_ip() {
        $ip = sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'] ?? '0.0.0.0'));

        // Only trust proxy headers when request comes from a known proxy
        $trusted_proxy = get_option('loiq_agent_trusted_proxy', '');
        if (!empty($trusted_proxy) && trim($ip) === trim($trusted_proxy)) {
            $proxy_headers = ['HTTP_CF_CONNECTING_IP', 'HTTP_X_FORWARDED_FOR', 'HTTP_X_REAL_IP'];
            foreach ($proxy_headers as $header) {
                if (!empty($_SERVER[$header])) {
                    $forwarded = sanitize_text_field(wp_unslash(explode(',', $_SERVER[$header])[0]));
                    if (filter_var(trim($forwarded), FILTER_VALIDATE_IP)) {
                        $ip = $forwarded;
                    }
                    break;
                }
            }
        }

        return trim($ip);
    }

    /**
     * Log request to database.
     * For auth failures (401/403), also logs to a separate auth audit trail.
     *
     * @param string $endpoint
     * @param int    $response_code
     * @param string $reason  Optional reason for auth failures
     */
    private function log_request($endpoint, $response_code, $reason = '') {
        global $wpdb;
        $table = $wpdb->prefix . 'loiq_agent_log';

        // Anonymize IP for GDPR (last octet = 0)
        $ip = $this->get_client_ip();
        $ip = preg_replace('/\.\d+$/', '.0', $ip);

        $wpdb->insert($table, [
            'endpoint'      => sanitize_text_field($endpoint),
            'ip_address'    => $ip,
            'response_code' => (int) $response_code,
            'created_at'    => current_time('mysql'),
        ], ['%s', '%s', '%d', '%s']);

        // Auth failure audit trail (401, 403, 429)
        if (in_array($response_code, [401, 403, 429], true)) {
            $this->log_auth_event($endpoint, $response_code, $ip, $reason);
        }
    }

    /**
     * Log auth-related events to options for admin visibility.
     * Keeps last 50 events in a rolling buffer.
     *
     * @since 3.1.0
     */
    private function log_auth_event($endpoint, $code, $ip, $reason) {
        $events = get_option('loiq_agent_auth_events', []);
        if (!is_array($events)) $events = [];

        $events[] = [
            'endpoint' => sanitize_text_field($endpoint),
            'code'     => (int) $code,
            'ip'       => $ip,
            'reason'   => sanitize_text_field(substr($reason, 0, 100)),
            'time'     => current_time('mysql'),
        ];

        // Keep last 50 events
        $events = array_slice($events, -50);
        update_option('loiq_agent_auth_events', $events, false);
    }

    // =========================================================================
    // ADMIN
    // =========================================================================

    /**
     * Check if current user has an allowed email domain for admin access.
     *
     * Only users with @ultrax.agency, @teamultrax.nl, or @teamultrax.com emails
     * can see the plugin in wp-admin. REST API access is unaffected (token-based).
     *
     * @return bool
     */
    public static function is_allowed_admin_user() {
        $user = wp_get_current_user();
        if (!$user || !$user->exists()) {
            return false;
        }
        $email = strtolower($user->user_email);
        foreach (self::ALLOWED_EMAIL_DOMAINS as $domain) {
            if (substr($email, -strlen('@' . $domain)) === '@' . $domain) {
                return true;
            }
        }
        return false;
    }

    /**
     * Hide plugin from the plugins list for non-allowed users.
     *
     * @param array $plugins
     * @return array
     */
    public function filter_plugin_visibility($plugins) {
        if (!self::is_allowed_admin_user()) {
            unset($plugins['loiq-wp-agent/loiq-wp-agent.php']);
        }
        return $plugins;
    }

    /**
     * Add admin menu under Tools (only for allowed email domains)
     */
    public function add_admin_menu() {
        if (!self::is_allowed_admin_user()) {
            return;
        }
        add_submenu_page(
            'tools.php',
            'LOIQ WP Agent',
            'LOIQ WP Agent',
            'manage_options',
            'loiq-wp-agent',
            [$this, 'render_admin_page']
        );
    }

    /**
     * Enqueue admin assets
     */
    public function enqueue_admin_assets($hook) {
        if ($hook !== 'tools_page_loiq-wp-agent') {
            return;
        }

        wp_enqueue_style('loiq-wp-agent-admin', false);
        wp_add_inline_style('loiq-wp-agent-admin', $this->get_admin_css());
    }

    /**
     * Get admin CSS
     */
    private function get_admin_css() {
        return '
            .loiq-wp-agent-wrap { max-width: 800px; }
            .loiq-wp-agent-wrap h1 { color: #1d2327; margin-bottom: 20px; }
            .loiq-card { background: #fff; border: 1px solid #c3c4c7; border-radius: 4px; padding: 20px; margin-bottom: 20px; }
            .loiq-card h2 { margin-top: 0; padding-bottom: 10px; border-bottom: 1px solid #eee; }
            .loiq-token-display { background: #f0f0f1; padding: 15px; border-radius: 4px; font-family: monospace; font-size: 14px; word-break: break-all; margin: 15px 0; }
            .loiq-token-new { background: #d4edda; border: 1px solid #28a745; }
            .loiq-token-new::before { content: "NIEUW - Kopieer nu! "; font-weight: bold; color: #155724; }
            .loiq-status { display: inline-block; padding: 5px 12px; border-radius: 20px; font-weight: 500; }
            .loiq-status-active { background: #d4edda; color: #155724; }
            .loiq-status-inactive { background: #f8d7da; color: #721c24; }
            .loiq-btn { margin-right: 10px !important; }
            .loiq-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
            .loiq-table th, .loiq-table td { padding: 10px; text-align: left; border-bottom: 1px solid #eee; }
            .loiq-table th { background: #f6f7f7; font-weight: 500; }
            .loiq-code { font-family: monospace; font-size: 12px; background: #f0f0f1; padding: 2px 6px; border-radius: 3px; }
            .loiq-log-200 { color: #155724; }
            .loiq-log-401, .loiq-log-403, .loiq-log-429 { color: #721c24; }
            .loiq-log-503 { color: #856404; }
            .loiq-help { background: #e7f3fe; border-left: 4px solid #2271b1; padding: 12px 15px; margin: 15px 0; }
            .loiq-help code { background: #d4e5f7; }
            .loiq-power-modes label { display: block; padding: 8px 0; font-size: 14px; }
            .loiq-power-modes input[type="checkbox"] { margin-right: 8px; }
            .loiq-power-modes .description { color: #646970; margin-left: 26px; display: block; font-size: 12px; }
            .loiq-snapshot-actions { white-space: nowrap; }
            .loiq-badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 500; }
            .loiq-badge-executed { background: #d4edda; color: #155724; }
            .loiq-badge-dryrun { background: #fff3cd; color: #856404; }
            .loiq-badge-rollback { background: #d1ecf1; color: #0c5460; }
        ';
    }

    /**
     * Render admin page
     */
    public function render_admin_page() {
        // Get status
        $enabled_until = (int) get_option('loiq_agent_enabled_until', 0);
        $is_active = $enabled_until > time();
        $new_token = get_transient('loiq_agent_new_token');
        $mu_plugin_installed = file_exists(ABSPATH . 'wp-content/mu-plugins/' . self::MU_PLUGIN_FILE);

        // Get request log
        global $wpdb;
        $log_table = $wpdb->prefix . 'loiq_agent_log';
        $table_exists = $wpdb->get_var($wpdb->prepare("SHOW TABLES LIKE %s", $log_table)) === $log_table;
        $recent_requests = $table_exists ? $wpdb->get_results(
            $wpdb->prepare("SELECT * FROM {$wpdb->prefix}loiq_agent_log ORDER BY created_at DESC LIMIT %d", 20)
        ) : [];

        ?>
        <div class="wrap loiq-wp-agent-wrap">
            <h1>LOIQ WP Agent</h1>

            <?php if ($new_token): ?>
            <div class="loiq-card">
                <h2>Je Access Token</h2>
                <p><strong>Kopieer dit token nu!</strong> Het wordt niet meer getoond na het verlaten van deze pagina.</p>
                <div class="loiq-token-display loiq-token-new" id="new-token"><?php echo esc_html($new_token); ?></div>
                <button type="button" class="button button-primary" onclick="copyToken()">Kopieer Token</button>

                <h3 style="margin-top: 20px;">Terminal Prompt (copy-paste ready)</h3>
                <pre id="terminal-prompt" style="margin: 10px 0; padding: 15px; background: #1d2327; color: #50fa7b; font-family: monospace; font-size: 13px; border-radius: 4px; overflow-x: auto; cursor: pointer;" onclick="copyTerminal()">curl -s -H "X-Claude-Token: <?php echo esc_attr($new_token); ?>" <?php echo esc_url(rest_url('claude/v1/status')); ?> | python3 -m json.tool</pre>
                <button type="button" class="button" onclick="copyTerminal()">Kopieer Terminal Prompt</button>

                <h3 style="margin-top: 20px;">AI Dev Prompt (geef aan je developer)</h3>
                <pre id="ai-dev-prompt" style="margin: 10px 0; padding: 15px; background: #1a1a2e; color: #e0e0ff; font-family: monospace; font-size: 12px; border-radius: 4px; overflow-x: auto; white-space: pre-wrap; cursor: pointer;" onclick="copyAiPrompt()">LOIQ WP Agent actief op deze site. SLA DIT OP IN JE AUTO-MEMORY (token + base URL) zodat het beschikbaar blijft na compaction.

Site: <?php echo esc_url(home_url()); ?>

Base URL: <?php echo esc_url(rest_url('claude/')); ?>

Header: X-Claude-Token: <?php echo esc_attr($new_token); ?>

=== v1 Read Endpoints (geen power mode nodig) ===
- /v1/status         — WP/PHP versie, memory, debug mode
- /v1/errors         — Debug.log (?lines=50)
- /v1/plugins        — Alle plugins met status
- /v1/theme          — Actief thema + parent
- /v1/database       — Tabellen en sizes
- /v1/code-context   — Code context (?topic=divi|gravity-forms|woocommerce|acf|custom-post-types)
- /v1/styles         — CSS stylesheets
- /v1/forms          — Gravity Forms (?id=3 voor detail)
- /v1/page           — Pagina context (?url=/over-ons of ?id=42)

=== v2 Write Endpoints (power modes vereist) ===
- /v2/css/deploy     — CSS naar child theme/Divi/customizer
- /v2/content/update — Post/page content + meta updaten
- /v2/option/update  — Whitelisted WP options
- /v2/plugin/toggle  — Plugins activeren/deactiveren
- /v2/snippet/deploy — PHP snippet als mu-plugin
- /v2/snapshots      — Bekijk snapshots
- /v2/rollback       — Herstel snapshot

=== v3 Site Builder (power modes vereist) ===
Divi Builder:     /v3/divi/build, /v3/divi/parse, /v3/divi/validate, /v3/divi/modules
Theme Builder:    /v3/theme-builder/list, /v3/theme-builder/create, /v3/theme-builder/update, /v3/theme-builder/assign
Pages:            /v3/page/create, /v3/page/clone, /v3/page/list
Menus:            /v3/menu/create, /v3/menu/items/add, /v3/menu/assign, /v3/menu/mega-menu/configure
Media:            /v3/media/upload, /v3/media/search
Forms:            /v3/forms/create, /v3/forms/update, /v3/forms/embed
Child Theme:      /v3/child-theme/functions/append, /v3/child-theme/functions/remove
FacetWP:          /v3/facet/create, /v3/facet/template
Taxonomie:        /v3/taxonomy/list, /v3/taxonomy/create-term, /v3/taxonomy/assign

=== Workflow ===
1. Pagina's aanmaken (templates beschikbaar)  2. Media uploaden
3. Content vullen via Divi Builder  4. Menu's + Mega Menu
5. Theme Builder (global header/footer + blog templates)
6. CSS fine-tuning via child theme

Alle write endpoints hebben dry_run + snapshot/rollback. Rate limit: 10 writes/min.</pre>
                <button type="button" class="button button-primary" onclick="copyAiPrompt()">Kopieer AI Dev Prompt</button>
            </div>
            <?php delete_transient('loiq_agent_new_token'); ?>
            <?php endif; ?>

            <div class="loiq-card">
                <h2>Status</h2>
                <p>
                    <span class="loiq-status <?php echo $is_active ? 'loiq-status-active' : 'loiq-status-inactive'; ?>">
                        <?php echo $is_active ? 'Actief' : 'Uitgeschakeld'; ?>
                    </span>
                    <?php if ($is_active): ?>
                        &nbsp; tot <?php echo date_i18n('d-m-Y H:i', $enabled_until); ?>
                        (<?php echo human_time_diff(time(), $enabled_until); ?> resterend)
                    <?php endif; ?>
                </p>

                <p>
                    <?php if ($is_active): ?>
                        <button type="button" class="button loiq-btn" onclick="disableDebug()">Uitschakelen</button>
                    <?php endif; ?>
                    <button type="button" class="button loiq-btn" onclick="enableDebug(1)">Activeer 1 uur</button>
                    <button type="button" class="button loiq-btn" onclick="enableDebug(24)">Activeer 24 uur</button>
                    <button type="button" class="button loiq-btn" onclick="enableDebug(168)">Activeer 1 week</button>
                </p>

                <?php if ($mu_plugin_installed): ?>
                <div class="loiq-help" style="margin-top: 15px;">
                    <strong>Managed Debug Logging actief.</strong>
                    WP_DEBUG_LOG wordt automatisch aan/uit gezet met de timer hierboven.
                    <?php if ($is_active): ?>
                        Debug logging is nu <strong>AAN</strong>.
                    <?php else: ?>
                        Debug logging is nu <strong>UIT</strong>.
                    <?php endif; ?>
                    <br><small>Opt-out: voeg <code>define('LOIQ_AGENT_UNMANAGED', true);</code> toe aan wp-config.php</small>
                </div>
                <?php else: ?>
                <div class="loiq-help" style="margin-top: 15px; border-left-color: #dba617;">
                    <strong>Managed Debug Logging niet actief.</strong>
                    <button type="button" class="button button-small" onclick="installMuPlugin()">Installeer mu-plugin</button>
                    <br><small>Koppelt WP_DEBUG_LOG aan de timer zodat debug logging automatisch stopt.</small>
                </div>
                <?php endif; ?>
            </div>

            <div class="loiq-card">
                <h2>Token Beheer</h2>
                <p>
                    <button type="button" class="button" onclick="regenerateToken()">Regenereer Token</button>
                    <span class="description">Dit maakt het huidige token ongeldig.</span>
                </p>
            </div>

            <div class="loiq-card">
                <h2>Gebruik</h2>
                <div class="loiq-help">
                    <p><strong>Endpoint:</strong> <code><?php echo esc_url(rest_url('claude/v1/status')); ?></code></p>
                    <p><strong>Header:</strong> <code>X-Claude-Token: &lt;jouw-token&gt;</code></p>
                    <p><strong>Voorbeeld:</strong></p>
                    <pre style="margin: 10px 0; padding: 10px; background: #f0f0f1; overflow-x: auto;">curl -H "X-Claude-Token: TOKEN" <?php echo esc_url(rest_url('claude/v1/status')); ?></pre>
                </div>

                <h3>Read Endpoints (v1)</h3>
                <table class="loiq-table">
                    <tr><th>Endpoint</th><th>Beschrijving</th></tr>
                    <tr><td><code>GET /claude/v1/status</code></td><td>WP versie, PHP, memory, debug mode</td></tr>
                    <tr><td><code>GET /claude/v1/errors</code></td><td>Laatste regels debug.log (?lines=50)</td></tr>
                    <tr><td><code>GET /claude/v1/plugins</code></td><td>Plugins lijst met update status</td></tr>
                    <tr><td><code>GET /claude/v1/theme</code></td><td>Actief thema info</td></tr>
                    <tr><td><code>GET /claude/v1/database</code></td><td>Database tabellen info (geen data)</td></tr>
                    <tr><td><code>GET /claude/v1/code-context</code></td><td>Code context (?topic=gravity-forms|woocommerce|divi|acf|...)</td></tr>
                    <tr><td><code>GET /claude/v1/styles</code></td><td>CSS stylesheets, customizer CSS, theme CSS</td></tr>
                    <tr><td><code>GET /claude/v1/forms</code></td><td>Gravity Forms structuur (?id=3 voor detail)</td></tr>
                    <tr><td><code>GET /claude/v1/page</code></td><td>Pagina context (?url=/over-ons of ?id=42)</td></tr>
                </table>

                <h3>Write Endpoints (v2) — vereist Power Mode</h3>
                <table class="loiq-table">
                    <tr><th>Endpoint</th><th>Power Mode</th><th>Beschrijving</th></tr>
                    <tr><td><code>POST /claude/v2/css/deploy</code></td><td>css</td><td>CSS deployen naar child theme, Divi, of customizer</td></tr>
                    <tr><td><code>POST /claude/v2/option/update</code></td><td>options</td><td>Whitelisted WP opties bijwerken</td></tr>
                    <tr><td><code>POST /claude/v2/plugin/toggle</code></td><td>plugins</td><td>Plugin activeren/deactiveren</td></tr>
                    <tr><td><code>POST /claude/v2/content/update</code></td><td>content</td><td>Post/pagina content bijwerken</td></tr>
                    <tr><td><code>POST /claude/v2/snippet/deploy</code></td><td>snippets</td><td>PHP snippet deployen als mu-plugin</td></tr>
                    <tr><td><code>POST /claude/v2/rollback</code></td><td>&mdash;</td><td>Snapshot terugdraaien</td></tr>
                    <tr><td><code>GET /claude/v2/snapshots</code></td><td>&mdash;</td><td>Recente snapshots lijst</td></tr>
                    <tr><td><code>GET /claude/v2/power-modes</code></td><td>&mdash;</td><td>Huidige power mode status</td></tr>
                </table>

                <h3>Site Builder Endpoints (v3) — vereist Power Mode</h3>
                <table class="loiq-table">
                    <tr><th>Endpoint</th><th>Power Mode</th><th>Beschrijving</th></tr>
                    <tr><td><code>POST /claude/v3/page/create</code></td><td>content</td><td>Pagina aanmaken met Divi content of template</td></tr>
                    <tr><td><code>POST /claude/v3/page/clone</code></td><td>content</td><td>Pagina dupliceren als draft</td></tr>
                    <tr><td><code>GET /claude/v3/page/list</code></td><td>&mdash;</td><td>Pagina's lijst met status en Divi info</td></tr>
                    <tr><td><code>POST /claude/v3/divi/build</code></td><td>divi_builder</td><td>JSON → Divi shortcode</td></tr>
                    <tr><td><code>POST /claude/v3/divi/parse</code></td><td>&mdash;</td><td>Divi shortcode → JSON</td></tr>
                    <tr><td><code>POST /claude/v3/divi/validate</code></td><td>&mdash;</td><td>Shortcode structuur valideren</td></tr>
                    <tr><td><code>GET /claude/v3/divi/modules</code></td><td>&mdash;</td><td>Module registry</td></tr>
                    <tr><td><code>GET /claude/v3/divi/templates</code></td><td>&mdash;</td><td>Page template library</td></tr>
                    <tr><td><code>GET /claude/v3/theme-builder/list</code></td><td>&mdash;</td><td>Theme Builder templates</td></tr>
                    <tr><td><code>POST /claude/v3/theme-builder/create</code></td><td>divi_builder</td><td>Template aanmaken</td></tr>
                    <tr><td><code>POST /claude/v3/theme-builder/update</code></td><td>divi_builder</td><td>Template content updaten</td></tr>
                    <tr><td><code>POST /claude/v3/theme-builder/assign</code></td><td>divi_builder</td><td>Template condities toewijzen</td></tr>
                    <tr><td><code>GET /claude/v3/child-theme/status</code></td><td>&mdash;</td><td>Child theme status + bestanden</td></tr>
                    <tr><td><code>POST /claude/v3/child-theme/create</code></td><td>child_theme</td><td>Child theme scaffolden (style.css + functions.php)</td></tr>
                    <tr><td><code>POST /claude/v3/child-theme/functions/append</code></td><td>child_theme</td><td>Tagged block toevoegen aan functions.php</td></tr>
                    <tr><td><code>POST /claude/v3/child-theme/functions/remove</code></td><td>child_theme</td><td>Tagged block verwijderen</td></tr>
                    <tr><td><code>GET /claude/v3/child-theme/functions/list</code></td><td>&mdash;</td><td>Tagged blocks lijst</td></tr>
                    <tr><td><code>POST /claude/v3/menu/create</code></td><td>menus</td><td>Menu aanmaken</td></tr>
                    <tr><td><code>POST /claude/v3/menu/items/add</code></td><td>menus</td><td>Menu items toevoegen</td></tr>
                    <tr><td><code>POST /claude/v3/menu/assign</code></td><td>menus</td><td>Menu toewijzen aan locatie</td></tr>
                    <tr><td><code>POST /claude/v3/media/upload</code></td><td>media</td><td>Afbeelding uploaden (base64 of URL)</td></tr>
                    <tr><td><code>GET /claude/v3/media/search</code></td><td>&mdash;</td><td>Media library doorzoeken</td></tr>
                    <tr><td><code>POST /claude/v3/forms/create</code></td><td>forms</td><td>Gravity Forms formulier aanmaken</td></tr>
                    <tr><td><code>POST /claude/v3/forms/update</code></td><td>forms</td><td>Formulier bewerken</td></tr>
                    <tr><td><code>POST /claude/v3/facet/create</code></td><td>facets</td><td>FacetWP facet aanmaken</td></tr>
                    <tr><td><code>POST /claude/v3/taxonomy/create-term</code></td><td>content</td><td>Taxonomy term aanmaken</td></tr>
                    <tr><td><code>POST /claude/v3/taxonomy/assign</code></td><td>content</td><td>Terms toewijzen aan post</td></tr>
                </table>
            </div>

            <div class="loiq-card">
                <h2>IP Whitelist (optioneel)</h2>
                <p>Laat leeg om alle IPs toe te staan. Eén IP per regel.</p>
                <form method="post" action="options.php">
                    <?php settings_fields('loiq_agent_settings'); ?>
                    <textarea name="loiq_agent_ip_whitelist" rows="4" style="width: 100%; font-family: monospace;"><?php echo esc_textarea(get_option('loiq_agent_ip_whitelist', '')); ?></textarea>
                    <?php submit_button('Opslaan', 'secondary'); ?>
                </form>
            </div>

            <?php
            // v2.0: Power Modes
            $power_modes = LOIQ_Agent_Safeguards::get_power_modes();
            $mode_labels = [
                'css'          => ['CSS Deploy', 'CSS injecteren in child theme, Divi custom CSS, of customizer'],
                'options'      => ['Option Updates', 'Whitelisted WP opties bijwerken (blogname, timezone, etc.)'],
                'plugins'      => ['Plugin Toggle', 'Plugins activeren/deactiveren via API'],
                'content'      => ['Content Updates', 'Post/pagina titel, content, meta, pages en taxonomies bijwerken'],
                'snippets'     => ['Code Snippets', 'PHP snippets deployen als mu-plugin'],
                'divi_builder' => ['Divi Builder', 'Divi shortcodes bouwen, Theme Builder templates, Library items'],
                'child_theme'  => ['Child Theme', 'functions.php tagged blocks toevoegen/verwijderen'],
                'menus'        => ['Menu Management', 'WP menus aanmaken, items toevoegen, Max Mega Menu configuratie'],
                'media'        => ['Media Upload', 'Afbeeldingen uploaden naar media library (max 5MB)'],
                'forms'        => ['Gravity Forms', 'Formulieren aanmaken, bewerken en verwijderen via GFAPI'],
                'facets'       => ['FacetWP', 'Facets en templates aanmaken/bewerken'],
            ];
            ?>
            <div class="loiq-card">
                <h2>Power Modes (v3.0)</h2>
                <p>Per-categorie write permissions. Standaard alles uitgeschakeld (fail-closed).</p>
                <div class="loiq-power-modes">
                    <?php foreach ($mode_labels as $key => $info): ?>
                    <label>
                        <input type="checkbox" name="power_mode_<?php echo esc_attr($key); ?>"
                               <?php checked(!empty($power_modes[$key])); ?>
                               onchange="savePowerModes()">
                        <?php echo esc_html($info[0]); ?>
                        <span class="description"><?php echo esc_html($info[1]); ?></span>
                    </label>
                    <?php endforeach; ?>
                </div>
                <p style="margin-top: 10px;">
                    <button type="button" class="button" onclick="savePowerModes()">Opslaan</button>
                    <span class="description">Write rate limit: <?php echo LOIQ_Agent_Safeguards::WRITE_RATE_LIMIT_MINUTE; ?>/min, <?php echo LOIQ_Agent_Safeguards::WRITE_RATE_LIMIT_HOUR; ?>/uur</span>
                </p>
            </div>

            <?php
            // v2.0: Snapshots
            $snapshots = LOIQ_Agent_Safeguards::get_snapshots(10);
            ?>
            <div class="loiq-card">
                <h2>Recente Snapshots (v2.0)</h2>
                <?php if (empty($snapshots)): ?>
                    <p>Nog geen snapshots. Snapshots worden aangemaakt bij write operaties via de v2 API.</p>
                <?php else: ?>
                <table class="loiq-table">
                    <tr><th>ID</th><th>Type</th><th>Target</th><th>Status</th><th>Tijd</th><th>Actie</th></tr>
                    <?php foreach ($snapshots as $snap): ?>
                    <tr>
                        <td><?php echo esc_html($snap['id']); ?></td>
                        <td><code><?php echo esc_html($snap['action_type']); ?></code></td>
                        <td class="loiq-code"><?php echo esc_html(substr($snap['target_key'], 0, 40)); ?></td>
                        <td>
                            <?php if ($snap['rolled_back']): ?>
                                <span class="loiq-badge loiq-badge-rollback">Teruggedraaid</span>
                            <?php elseif ($snap['executed']): ?>
                                <span class="loiq-badge loiq-badge-executed">Uitgevoerd</span>
                            <?php else: ?>
                                <span class="loiq-badge loiq-badge-dryrun">Dry-run</span>
                            <?php endif; ?>
                        </td>
                        <td><?php echo esc_html($snap['created_at']); ?></td>
                        <td class="loiq-snapshot-actions">
                            <?php if ($snap['executed'] && !$snap['rolled_back']): ?>
                                <button type="button" class="button button-small" onclick="rollbackSnapshot(<?php echo esc_attr($snap['id']); ?>)">Rollback</button>
                            <?php else: ?>
                                &mdash;
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </div>

            <?php
            // v2.0: Deployed Snippets
            $deployed_snippets = LOIQ_Agent_Safeguards::get_deployed_snippets();
            ?>
            <div class="loiq-card">
                <h2>Gedeployde Snippets (v2.0)</h2>
                <?php if (empty($deployed_snippets)): ?>
                    <p>Geen actieve snippets. Deploy via <code>POST /claude/v2/snippet/deploy</code>.</p>
                <?php else: ?>
                <table class="loiq-table">
                    <tr><th>Naam</th><th>Bestand</th><th>Grootte</th><th>Laatst gewijzigd</th><th>Actie</th></tr>
                    <?php foreach ($deployed_snippets as $snippet): ?>
                    <tr>
                        <td><strong><?php echo esc_html($snippet['name']); ?></strong></td>
                        <td class="loiq-code"><?php echo esc_html($snippet['file']); ?></td>
                        <td><?php echo esc_html(size_format($snippet['size'])); ?></td>
                        <td><?php echo esc_html($snippet['modified']); ?></td>
                        <td>
                            <button type="button" class="button button-small" style="color:#721c24;" onclick="removeSnippet('<?php echo esc_js($snippet['name']); ?>')">Verwijderen</button>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
                <p><small><?php echo count($deployed_snippets); ?>/<?php echo LOIQ_Agent_Safeguards::SNIPPET_MAX_ACTIVE; ?> slots gebruikt</small></p>
                <?php endif; ?>
            </div>

            <?php if (!empty($recent_requests)): ?>
            <div class="loiq-card">
                <h2>Request Log (laatste 20)</h2>
                <p><button type="button" class="button" onclick="clearLog()">Log Wissen</button></p>
                <table class="loiq-table">
                    <tr><th>Tijd</th><th>Endpoint</th><th>IP</th><th>Status</th></tr>
                    <?php foreach ($recent_requests as $req): ?>
                    <tr>
                        <td><?php echo esc_html($req->created_at); ?></td>
                        <td><code><?php echo esc_html($req->endpoint); ?></code></td>
                        <td class="loiq-code"><?php echo esc_html($req->ip_address); ?></td>
                        <td class="loiq-log-<?php echo esc_attr($req->response_code); ?>"><?php echo esc_html($req->response_code); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
            <?php endif; ?>

            <div class="loiq-card">
                <h2>Security Features</h2>
                <ul>
                    <li>Token verificatie (password_hash)</li>
                    <li>HTTPS verplicht (behalve localhost)</li>
                    <li>Read rate limiting: <?php echo self::RATE_LIMIT_MINUTE; ?>/min, <?php echo self::RATE_LIMIT_HOUR; ?>/uur</li>
                    <li>Write rate limiting: <?php echo LOIQ_Agent_Safeguards::WRITE_RATE_LIMIT_MINUTE; ?>/min, <?php echo LOIQ_Agent_Safeguards::WRITE_RATE_LIMIT_HOUR; ?>/uur</li>
                    <li>Auto-disable timer (endpoints + debug logging + power modes)</li>
                    <li>IP whitelist (optioneel)</li>
                    <li>Request logging met GDPR IP anonimisatie</li>
                    <li>Per-categorie power modes (fail-closed)</li>
                    <li>Pre-edit snapshots met rollback</li>
                    <li>Dry-run mode voor alle write endpoints</li>
                    <li>Option whitelist (deny-by-default)</li>
                    <li>Snippet veiligheidsscanner (blokkeert eval, exec, etc.)</li>
                </ul>
            </div>
        </div>

        <script>
        function copyToken() {
            var token = document.getElementById('new-token').textContent.replace('NIEUW - Kopieer nu! ', '');
            navigator.clipboard.writeText(token).then(function() {
                alert('Token gekopieerd!');
            });
        }

        function copyTerminal() {
            var prompt = document.getElementById('terminal-prompt').textContent;
            navigator.clipboard.writeText(prompt).then(function() {
                alert('Terminal prompt gekopieerd!');
            });
        }

        function copyAiPrompt() {
            var prompt = document.getElementById('ai-dev-prompt').textContent;
            navigator.clipboard.writeText(prompt).then(function() {
                alert('AI Dev prompt gekopieerd! Geef aan je developer.');
            });
        }

        function regenerateToken() {
            if (!confirm('Weet je zeker dat je een nieuw token wilt genereren? Het huidige token wordt ongeldig.')) return;

            jQuery.post(ajaxurl, {
                action: 'loiq_agent_regenerate_token',
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function enableDebug(hours) {
            jQuery.post(ajaxurl, {
                action: 'loiq_agent_enable',
                hours: hours,
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function disableDebug() {
            jQuery.post(ajaxurl, {
                action: 'loiq_agent_disable',
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function clearLog() {
            if (!confirm('Weet je zeker dat je de log wilt wissen?')) return;

            jQuery.post(ajaxurl, {
                action: 'loiq_agent_clear_log',
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function installMuPlugin() {
            jQuery.post(ajaxurl, {
                action: 'loiq_agent_install_mu',
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function savePowerModes() {
            var modes = {};
            <?php foreach (array_keys($mode_labels) as $key): ?>
            modes['<?php echo esc_js($key); ?>'] = document.querySelector('input[name="power_mode_<?php echo esc_js($key); ?>"]').checked ? 1 : 0;
            <?php endforeach; ?>

            jQuery.post(ajaxurl, {
                action: 'loiq_agent_save_power_modes',
                modes: modes,
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function rollbackSnapshot(id) {
            if (!confirm('Snapshot #' + id + ' terugdraaien? De vorige staat wordt hersteld.')) return;

            jQuery.post(ajaxurl, {
                action: 'loiq_agent_rollback',
                snapshot_id: id,
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    alert('Snapshot #' + id + ' teruggedraaid.');
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }

        function removeSnippet(name) {
            if (!confirm('Snippet "' + name + '" verwijderen? Dit kan de site beinvloeden.')) return;

            jQuery.post(ajaxurl, {
                action: 'loiq_agent_remove_snippet',
                name: name,
                _wpnonce: '<?php echo wp_create_nonce('loiq_agent_nonce'); ?>'
            }, function(response) {
                if (response.success) {
                    location.reload();
                } else {
                    alert('Fout: ' + response.data);
                }
            });
        }
        </script>
        <?php
    }

    // =========================================================================
    // AJAX HANDLERS
    // =========================================================================

    /**
     * Regenerate token
     */
    public function ajax_regenerate_token() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $token = bin2hex(random_bytes(32));
        update_option('loiq_agent_token_hash', password_hash($token, PASSWORD_DEFAULT));
        set_transient('loiq_agent_new_token', $token, 300);

        wp_send_json_success();
    }

    /**
     * Enable debug for X hours
     */
    public function ajax_enable() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $hours = absint(sanitize_text_field($_POST['hours'] ?? self::DEFAULT_HOURS));
        $hours = max(1, min(168, $hours)); // 1 hour to 1 week

        update_option('loiq_agent_enabled_until', time() + ($hours * 3600));

        wp_send_json_success();
    }

    /**
     * Disable debug
     */
    public function ajax_disable() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        update_option('loiq_agent_enabled_until', 0);

        wp_send_json_success();
    }

    /**
     * Clear request log
     */
    public function ajax_clear_log() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        global $wpdb;
        $wpdb->query($wpdb->prepare("TRUNCATE TABLE {$wpdb->prefix}loiq_agent_log"));

        wp_send_json_success();
    }

    /**
     * Install mu-plugin for managed debug logging
     */
    public function ajax_install_mu() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $result = self::install_mu_plugin();
        if ($result === true) {
            wp_send_json_success();
        } else {
            wp_send_json_error($result);
        }
    }

    // =========================================================================
    // v2.0 AJAX HANDLERS
    // =========================================================================

    /**
     * Save power modes from admin UI
     */
    public function ajax_save_power_modes() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $modes = isset($_POST['modes']) && is_array($_POST['modes']) ? $_POST['modes'] : [];
        $clean = [];
        foreach (['css', 'options', 'plugins', 'content', 'snippets', 'divi_builder', 'child_theme', 'menus', 'media', 'forms', 'facets'] as $key) {
            $clean[$key] = !empty($modes[$key]);
        }

        LOIQ_Agent_Safeguards::set_power_modes($clean);
        wp_send_json_success();
    }

    /**
     * Rollback a snapshot from admin UI
     */
    public function ajax_rollback() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $snapshot_id = absint($_POST['snapshot_id'] ?? 0);
        if ($snapshot_id <= 0) {
            wp_send_json_error('Ongeldig snapshot ID');
        }

        $result = LOIQ_Agent_Safeguards::rollback_snapshot($snapshot_id);
        if (is_wp_error($result)) {
            wp_send_json_error($result->get_error_message());
        }

        wp_send_json_success($result);
    }

    /**
     * Remove a deployed snippet from admin UI
     */
    public function ajax_remove_snippet() {
        check_ajax_referer('loiq_agent_nonce');

        if (!current_user_can('manage_options')) {
            wp_send_json_error('Geen toegang');
        }

        $name = sanitize_file_name($_POST['name'] ?? '');
        if (empty($name)) {
            wp_send_json_error('Snippet naam ontbreekt');
        }

        $result = LOIQ_Agent_Safeguards::remove_snippet($name);
        if (is_wp_error($result)) {
            wp_send_json_error($result->get_error_message());
        }

        wp_send_json_success();
    }
}

/**
 * GitHub Auto-Updater
 */
class LOIQ_WP_Agent_Updater {

    private $plugin_file;
    private $plugin_slug;
    private $repo;
    private $cache_key = 'loiq_agent_update_check';
    private $cache_expiry = 43200; // 12 hours

    public function __construct() {
        $this->plugin_file = plugin_basename(LOIQ_AGENT_PATH . 'loiq-wp-agent.php');
        $this->plugin_slug = dirname($this->plugin_file);
        $this->repo = LOIQ_AGENT_GITHUB_REPO;

        // Hook into WP update system
        add_filter('pre_set_site_transient_update_plugins', [$this, 'check_for_update']);
        add_filter('plugins_api', [$this, 'plugin_info'], 10, 3);
        add_filter('upgrader_source_selection', [$this, 'fix_source_dir'], 10, 4);

        // Add "Check for updates" link on plugins page
        add_filter('plugin_action_links_' . $this->plugin_file, [$this, 'add_check_update_link']);
        add_action('admin_init', [$this, 'handle_check_update']);
        add_action('admin_notices', [$this, 'show_update_notice']);
    }

    /**
     * Check GitHub for new release
     */
    public function check_for_update($transient) {
        if (empty($transient->checked)) {
            return $transient;
        }

        $remote = $this->get_remote_version();

        if ($remote && version_compare(LOIQ_AGENT_VERSION, $remote['version'], '<')) {
            $transient->response[$this->plugin_file] = (object) [
                'slug'        => $this->plugin_slug,
                'plugin'      => $this->plugin_file,
                'new_version' => $remote['version'],
                'url'         => "https://github.com/{$this->repo}",
                'package'     => $remote['download_url'],
                'icons'       => [],
                'banners'     => [],
                'tested'      => get_bloginfo('version'),
                'requires_php'=> '7.4',
            ];
        }

        return $transient;
    }

    /**
     * Provide plugin info for the update modal
     */
    public function plugin_info($result, $action, $args) {
        if ($action !== 'plugin_information' || ($args->slug ?? '') !== $this->plugin_slug) {
            return $result;
        }

        $remote = $this->get_remote_version();

        if (!$remote) {
            return $result;
        }

        return (object) [
            'name'            => 'LOIQ WP Agent',
            'slug'            => $this->plugin_slug,
            'version'         => $remote['version'],
            'author'          => '<a href="https://loiq.nl">LOIQ</a>',
            'author_profile'  => 'https://loiq.nl',
            'homepage'        => "https://github.com/{$this->repo}",
            'requires'        => '5.8',
            'requires_php'    => '7.4',
            'tested'          => get_bloginfo('version'),
            'download_link'   => $remote['download_url'],
            'sections'        => [
                'description'  => 'Beveiligde REST API endpoints voor Claude CLI site debugging.',
                'changelog'    => $remote['changelog'] ?? 'Zie GitHub releases voor changelog.',
            ],
        ];
    }

    /**
     * Fix folder name after unzip (GitHub adds -tag suffix)
     */
    public function fix_source_dir($source, $remote_source, $upgrader, $hook_extra) {
        if (!isset($hook_extra['plugin']) || $hook_extra['plugin'] !== $this->plugin_file) {
            return $source;
        }

        global $wp_filesystem;

        $new_source = trailingslashit($remote_source) . $this->plugin_slug . '/';

        if ($source !== $new_source && $wp_filesystem->move($source, $new_source)) {
            return $new_source;
        }

        return $source;
    }

    /**
     * Show admin notice after update check
     */
    public function show_update_notice() {
        $message = get_transient('loiq_update_notice');
        if (!$message) return;
        delete_transient('loiq_update_notice');
        $type = strpos($message, 'up-to-date') !== false ? 'info' : 'warning';
        echo '<div class="notice notice-' . $type . ' is-dismissible"><p><strong>' . esc_html($message) . '</strong></p></div>';
    }

    /**
     * Add "Check for updates" action link on the plugins page
     */
    public function add_check_update_link($links) {
        $check_url = wp_nonce_url(
            admin_url('plugins.php?loiq_check_update=1'),
            'loiq_check_update'
        );
        $links['check_update'] = '<a href="' . esc_url($check_url) . '">Check for updates</a>';
        return $links;
    }

    /**
     * Handle the "Check for updates" click — clear cache, force re-check
     */
    public function handle_check_update() {
        if (empty($_GET['loiq_check_update']) || !current_user_can('update_plugins')) {
            return;
        }

        check_admin_referer('loiq_check_update');

        // Clear our cache
        delete_transient($this->cache_key);

        // Force WordPress to re-check plugin updates
        delete_site_transient('update_plugins');
        wp_update_plugins();

        // Check if an update was found
        $remote = $this->get_remote_version();
        if ($remote && version_compare(LOIQ_AGENT_VERSION, $remote['version'], '<')) {
            $message = 'LOIQ WP Agent update gevonden: v' . $remote['version'];
        } else {
            $message = 'LOIQ WP Agent is up-to-date (v' . LOIQ_AGENT_VERSION . ')';
        }

        // Redirect back with admin notice
        set_transient('loiq_update_notice', $message, 30);
        wp_safe_redirect(admin_url('plugins.php'));
        exit;
    }

    /**
     * Get latest release info from GitHub
     */
    private function get_remote_version() {
        // Check cache first
        $cached = get_transient($this->cache_key);
        if ($cached !== false) {
            return $cached;
        }

        // Fetch from GitHub API
        $response = wp_remote_get(
            "https://api.github.com/repos/{$this->repo}/releases/latest",
            [
                'timeout' => 10,
                'headers' => [
                    'Accept' => 'application/vnd.github.v3+json',
                    'User-Agent' => 'WordPress/' . get_bloginfo('version'),
                ],
            ]
        );

        if (is_wp_error($response) || wp_remote_retrieve_response_code($response) !== 200) {
            return null;
        }

        $release = json_decode(wp_remote_retrieve_body($response), true);

        if (empty($release['tag_name'])) {
            return null;
        }

        // Remove 'v' prefix from version tag
        $version = ltrim($release['tag_name'], 'v');

        // Find zip asset or use zipball_url
        $download_url = $release['zipball_url'];
        foreach ($release['assets'] ?? [] as $asset) {
            if (substr($asset['name'], -4) === '.zip') {
                $download_url = $asset['browser_download_url'];
                break;
            }
        }

        $data = [
            'version'      => $version,
            'download_url' => $download_url,
            'changelog'    => $release['body'] ?? '',
            'published_at' => $release['published_at'] ?? '',
        ];

        // Cache result
        set_transient($this->cache_key, $data, $this->cache_expiry);

        return $data;
    }
}

// Initialize updater
new LOIQ_WP_Agent_Updater();

// Register settings
add_action('admin_init', function() {
    register_setting('loiq_agent_settings', 'loiq_agent_ip_whitelist', [
        'type' => 'string',
        'sanitize_callback' => 'sanitize_textarea_field',
    ]);

});

// Initialize
register_activation_hook(__FILE__, ['LOIQ_WP_Agent', 'on_activation']);
register_deactivation_hook(__FILE__, ['LOIQ_WP_Agent', 'on_deactivation']);
add_action('plugins_loaded', ['LOIQ_WP_Agent', 'get_instance']);
